/**
 * 北京精选热门路线（一期 3 条 + 二期扩充 17 条）。
 *
 * 里程与爬升为官方/权威/社区口径（来源逐条标注，禁止凭空估算）：
 * - A 级（官方）：妙峰山、潭王路（门头沟区政府「中国骑行地图」）、戒台寺（「京西骑迹」）、
 *   红井路（北京旅游网）、环十三陵两条（环十三陵骑行文化季规程）
 * - B 级（权威媒体）：解字石（野途网）
 * - C 级（社区码表，仅供参考）：其余各条，主要来自风云单车「北京著名爬坡点的坡度」
 *   社区坡度表及骑友双源印证
 * 几何为 OSM 路网 Dijkstra 选路产出的简化示意线，见 beijingTracks.ts；
 * geometryScope = 'core' 表示路径线仅覆盖核心精华段（长距离环线/往返路线）。
 */
import type { CuratedRoute } from '@/features/curatedRoutes/types'
import { BEIJING_TRACKS } from '@/features/curatedRoutes/beijingTracks'

export const BEIJING_CURATED_ROUTES: CuratedRoute[] = [
  {
    id: 'bj-miaofengshan',
    name: '妙峰山',
    region: 'beijing',
    area: '门头沟',
    distanceMeters: 19700,
    elevationGainMeters: 868,
    difficulty: 4,
    kind: 'climb',
    description:
      '北京「公路车圣地」：以妙峰山牌楼为起点沿妙峰山路登顶，前半程缓升、后半程陡增，连续两年为北京自行车联赛赛段。',
    tips: '3–11 月适宜，5 月底玫瑰谷花期最佳；山顶为死路终点，注意放坡安全；沿线补给点集中在涧沟村。',
    source: '门头沟区政府「中国骑行地图」（2024）',
    sourceGrade: 'A',
    tracks: BEIJING_TRACKS.miaofeng ?? [],
  },
  {
    id: 'bj-tanwanglu',
    name: '潭王路',
    region: 'beijing',
    area: '门头沟',
    distanceMeters: 29700,
    elevationGainMeters: 558,
    difficulty: 3,
    kind: 'climb',
    description:
      '连接 G108 与 G109 的京西经典：檀谷·慢闪公园出发，经潭柘寺、十字道至王平镇，蜿蜒曲折、车少景美，坡顶可远眺永定河。',
    tips: '两端起点均有小店补水；回程建议沿 G109 而非京西古道（后者碎石多不适合公路车）。',
    source: '门头沟区政府「中国骑行地图」（2024）',
    sourceGrade: 'A',
    tracks: BEIJING_TRACKS.tanwang ?? [],
  },
  {
    id: 'bj-jietaisi',
    name: '戒台寺',
    region: 'beijing',
    area: '门头沟',
    distanceMeters: 4960,
    elevationGainMeters: 213,
    difficulty: 2,
    kind: 'climb',
    description:
      '「骑圈第一课」：从苛罗坨沿 108 国道辅线爬至千年古刹戒台寺，短而友好，是检验进步的打卡赛段。',
    tips: '夏季日均可超 4000 人次骑行；山脚有骑行驿站（补水/简易维修）；可与潭王路串骑。',
    source: '门头沟区「京西骑迹」官方口径（2026）',
    sourceGrade: 'A',
    tracks: BEIJING_TRACKS.jietai ?? [],
  },
  {
    id: 'bj-hongjinglu',
    name: '红井路',
    region: 'beijing',
    area: '房山',
    distanceMeters: 18940,
    elevationGainMeters: 635,
    difficulty: 4,
    kind: 'climb',
    description:
      '房山「小川藏线」：从十渡沿盘山公路蜿蜒爬升至井儿峪方向垭口，连续发卡弯配合拒马河峡谷景观，最高点海拔约 905 米。',
    tips: '十渡起点海拔约 270 米；节假日景区车流大，建议早出发；弯道视线差，放坡务必控制车速。',
    source: '北京旅游网官方口径（全长 18.94km，最高点 905m）',
    sourceGrade: 'A',
    tracks: BEIJING_TRACKS.hjl ?? [],
  },
  {
    id: 'bj-huanshisanling-quanyou',
    name: '环十三陵·全龄友好线',
    region: 'beijing',
    area: '昌平',
    distanceMeters: 35000,
    elevationGainMeters: 274,
    difficulty: 2,
    kind: 'endurance',
    description:
      '昌平骑行文化季官方线路：自昌平城区经西关环岛入十三陵环陵路，串联昭陵、泰陵、献陵、长陵、定陵，路况平整、爬升温和。',
    tips: '适合家庭与新手拉练；神道景区段游客多注意避让；沿线补水方便。',
    source: '2025 环十三陵骑行文化季规程（35km 组）',
    sourceGrade: 'A',
    tracks: BEIJING_TRACKS.hsl ?? [],
  },
  {
    id: 'bj-huanshisanling-jinjie',
    name: '环十三陵·环陵进阶线',
    region: 'beijing',
    area: '昌平',
    distanceMeters: 55400,
    elevationGainMeters: 674,
    difficulty: 3,
    kind: 'endurance',
    description:
      '骑行文化季进阶线路：在环陵基础上扩大范围，绕行十三陵各陵与山区支线，里程与爬升全面上档，是京北耐力拉练经典。',
    tips: '建议携带充足补给；山区段手机信号弱，结伴骑行。',
    source: '2025 环十三陵骑行文化季规程（55.4km 组）',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: BEIJING_TRACKS.hsl2 ?? [],
  },
  {
    id: 'bj-jiezishi',
    name: '解字石',
    region: 'beijing',
    area: '昌平',
    distanceMeters: 12520,
    elevationGainMeters: 544,
    difficulty: 3,
    kind: 'climb',
    description:
      '昌平东北部经典爬坡：从长陵沿安四路方向爬至解字石村，前段缓升热身、后段 5%+ 稳定输出，垭口视野开阔。',
    tips: '可与大庄科、慈母山一带串骑；冬季背阴处易结冰。',
    source: '野途网路线库（均坡 4.14%）',
    sourceGrade: 'B',
    tracks: BEIJING_TRACKS.jzs ?? [],
  },
  {
    id: 'bj-sihai',
    name: '四海',
    region: 'beijing',
    area: '怀柔',
    distanceMeters: 21700,
    elevationGainMeters: 660,
    difficulty: 3,
    kind: 'climb',
    description:
      '怀柔「小环线」核心坡：九渡河起经黄花城方向爬至四海镇，全程无明显平路缓冲，是京北爬坡量的试金石。',
    tips: '坡度表分三段：前 14km 约 1.7%、中段 4.4km 约 6.1%、末段 3.3km 约 4.8%；四海镇可补给。',
    source: '社区坡度表 + 财经网骑游报道双源印证',
    sourceGrade: 'C',
    tracks: BEIJING_TRACKS.sh ?? [],
  },
  {
    id: 'bj-bailihualang',
    name: '百里山水画廊',
    region: 'beijing',
    area: '延庆',
    distanceMeters: 50000,
    elevationGainMeters: 600,
    difficulty: 3,
    kind: 'endurance',
    description:
      '延庆王牌骑游线：从白河堡水库沿白河峡谷一路向东至千家店，白河相伴、山峦如画，起伏平缓风景极佳。',
    tips: '白河堡水库段风大；千家店有餐饮补给；四季景色各异，秋季最佳。',
    source: '骑行路书平台 + 攻略媒体双源印证（白河堡→千家店约 50km）',
    sourceGrade: 'C',
    tracks: BEIJING_TRACKS.bll ?? [],
  },
  {
    id: 'bj-mangshan',
    name: '蟒山',
    region: 'beijing',
    area: '昌平',
    distanceMeters: 115000,
    elevationGainMeters: 488,
    difficulty: 3,
    kind: 'climb',
    description:
      '十三陵水库东侧的城区后花园：沿蟒山爬坡路盘旋登至森林公园，可俯瞰水库全景，是昌平骑友的日常练坡场。',
    tips: '路径线为爬坡核心段示意（山脚路口 → 森林公园大门）；115km 为社区环线拉练口径，沿途补给少自备。',
    source: '高校骑行社团拉练帖（社区码表口径）',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: BEIJING_TRACKS.ms ?? [],
  },
  {
    id: 'bj-huanghuacheng',
    name: '黄花城水长城',
    region: 'beijing',
    area: '怀柔',
    distanceMeters: 114850,
    elevationGainMeters: 862,
    difficulty: 3,
    kind: 'climb',
    description:
      '「长城戏水」经典目的地：九渡河起沿怀黄路方向爬至黄花城水长城景区，湖光山色与野长城同框。',
    tips: '路径线为九渡河→黄花城核心段示意；景区段节假日人多车多；往返全程为社区码表口径。',
    source: '高校骑行社团拉练帖（社区码表口径）',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: BEIJING_TRACKS.hhc ?? [],
  },
  {
    id: 'bj-yanxihu',
    name: '雁栖湖环线',
    region: 'beijing',
    area: '怀柔',
    distanceMeters: 120000,
    elevationGainMeters: 232,
    difficulty: 2,
    kind: 'endurance',
    description:
      '京郊平路耐力首选：绕雁栖湖骑行道与周边路网，湖景与会址建筑群相伴，几乎无爬升，适合恢复骑与团队活动。',
    tips: '路径线为环湖核心段示意（雁栖湖路）；全程环线为社区拉练口径；夏季湖边蚊虫多。',
    source: '高校骑行社团拉练帖（社区码表口径）',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: BEIJING_TRACKS.yxh ?? [],
  },
  {
    id: 'bj-gaoyaikou',
    name: '高崖口',
    region: 'beijing',
    area: '昌平',
    distanceMeters: 12300,
    elevationGainMeters: 730,
    difficulty: 4,
    kind: 'climb',
    description:
      '昌平西部名坡：从流村沿南雁路爬至高崖口垭口，均坡 5.9%，垭口观景台是京西群山的最佳观景位之一。',
    tips: '坡度表口径：村口拐弯~观景台 12.3km/730m/5.9%；垭口风大，备防风衣。',
    source: '风云单车「北京著名爬坡点的坡度」社区坡度表',
    sourceGrade: 'C',
    tracks: BEIJING_TRACKS.gyk ?? [],
  },
  {
    id: 'bj-dacun',
    name: '大村',
    region: 'beijing',
    area: '昌平',
    distanceMeters: 10300,
    elevationGainMeters: 516,
    difficulty: 4,
    kind: 'climb',
    description:
      '芹峪口起沿山路爬至大村，均坡 5.0%，与高崖口、老峪沟一带构成昌平西部爬坡组合，车少弯多。',
    tips: '坡度表口径：芹峪口~顶 10.3km/516m/5.0%；山中补给点少，自备水粮。',
    source: '风云单车「北京著名爬坡点的坡度」社区坡度表',
    sourceGrade: 'C',
    tracks: BEIJING_TRACKS.dc ?? [],
  },
  {
    id: 'bj-cibeiyu',
    name: '慈悲峪',
    region: 'beijing',
    area: '昌平',
    distanceMeters: 18400,
    elevationGainMeters: 315,
    difficulty: 2,
    kind: 'climb',
    description:
      '安四路上的长缓坡：兴寿起一路缓升至慈悲峪垭口，均坡仅 1.7%，是练踏频与有氧基础的好坡。',
    tips: '反爬（慈悲峪桥头~顶 2.95km/125m/4.3%）强度更高；安四路货车较多注意安全。',
    source: '风云单车「北京著名爬坡点的坡度」社区坡度表',
    sourceGrade: 'C',
    tracks: BEIJING_TRACKS.cby ?? [],
  },
  {
    id: 'bj-yangtaishan',
    name: '阳台山',
    region: 'beijing',
    area: '海淀',
    distanceMeters: 7060,
    elevationGainMeters: 372,
    difficulty: 3,
    kind: 'climb',
    description:
      '海淀近郊名坡：北安河方向爬向阳台山自然风景区，离城区最近的山地爬坡之一，晨练与课表首选。',
    tips: '路径线为北安河→景区方向爬坡段示意；社区坡度表另记 7.06km/372m（涧沟方向）；周末游人密集。',
    source: '风云单车「北京著名爬坡点的坡度」社区坡度表',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: BEIJING_TRACKS.yts ?? [],
  },
  {
    id: 'bj-chanfang',
    name: '禅房',
    region: 'beijing',
    area: '门头沟',
    distanceMeters: 8300,
    elevationGainMeters: 349,
    difficulty: 3,
    kind: 'climb',
    description:
      '妙峰山后山隐藏坡：从上苇甸方向爬至禅房村，林荫密布、几乎无车，是妙峰山主路之外的清静之选。',
    tips: '坡度表口径：大沟村桥头~顶 8.3km/349m/4.2%；后山路段窄，会车提前减速。',
    source: '风云单车「北京著名爬坡点的坡度」社区坡度表',
    sourceGrade: 'C',
    tracks: BEIJING_TRACKS.cf ?? [],
  },
  {
    id: 'bj-heichenlu',
    name: '黑陈路',
    region: 'beijing',
    area: '石景山',
    distanceMeters: 4700,
    elevationGainMeters: 270,
    difficulty: 3,
    kind: 'climb',
    description:
      '石景山短陡坡代表：从黑石头村爬至陈家沟方向，4.7km 里爬升 270 米，是城西车友的热身/冲刺坡。',
    tips: '坡度表口径：黑石头超市~茶棚 4.7km/270m/5.1%；可与模式口一带串骑。',
    source: '风云单车「北京著名爬坡点的坡度」社区坡度表',
    sourceGrade: 'C',
    tracks: BEIJING_TRACKS.hcl ?? [],
  },
  {
    id: 'bj-dongfanghong',
    name: '东方红隧道',
    region: 'beijing',
    area: '门头沟',
    distanceMeters: 7700,
    elevationGainMeters: 418,
    difficulty: 3,
    kind: 'climb',
    description:
      'G109 上的隧道坡：安家庄至富水峪之间翻越东方红隧道，东段 4.0km/214m/5.3%、西段 3.7km/204m/5.5%，隧道内照明良好。',
    tips: '隧道内请开车灯并靠右；可与潭王路组合成「拿下妙峰山」预热训练。',
    source: '风云单车「北京著名爬坡点的坡度」社区坡度表（两段合计）',
    sourceGrade: 'C',
    tracks: BEIJING_TRACKS.dfh ?? [],
  },
  {
    id: 'bj-shanba',
    name: '山吧',
    region: 'beijing',
    area: '怀柔',
    distanceMeters: 19800,
    elevationGainMeters: 455,
    difficulty: 3,
    kind: 'climb',
    description:
      '怀柔雁栖方向的经典进山坡：从雁栖镇沿雁栖湖路经官地爬向莲花池顶，末段 3.6km 均坡 6.1% 定胜负。',
    tips: '路径线为雁栖→官地核心段示意；坡度表分段：10.3km/0.9% + 5.9km/2.4% + 3.6km/6.1%；周末返回车流大。',
    source: '风云单车「北京著名爬坡点的坡度」社区坡度表（分段均坡推算）',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: BEIJING_TRACKS.sb ?? [],
  },
]
