/**
 * 全国精选热门路线（二期里程碑 2）：西安 / 杭州 / 台州 / 深圳 / 成都 / 昆明各 1 条。
 *
 * 数据口径同 beijing.ts：里程/爬升带权威来源与三级可信度标注，
 * 几何由 scripts/generate-curated-routes.mjs 从 OSM 路网产出（nationalTracks.ts）。
 */
import { NATIONAL_TRACKS } from '@/features/curatedRoutes/nationalTracks'
import type { CuratedRoute } from '@/features/curatedRoutes/types'

export const NATIONAL_CURATED_ROUTES: CuratedRoute[] = [
  {
    id: 'tz-fengshan',
    name: '椒江环枫山绿道',
    region: 'taizhou',
    area: '椒江区',
    distanceMeters: 3100,
    elevationGainMeters: 3,
    difficulty: 1,
    kind: 'endurance',
    description:
      '椒江城区的短途环山绿道，3.1公里贴着枫山脚蜿蜒，一侧是城市、一侧是山林，塑胶步道与自行车道并存，是市中心最便利的“下楼就能骑”的微型线。',
    tips: '距离极短、坡度缓，适合热身与夜骑；沿途设租赁点，注意与行人共用路面、减速避让。',
    source: '浙江在线：椒江环枫山绿道全长3100米，沿山体而建，分西枫山路、东枫山路、建设路三段；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['tz-fengshan'] ?? [],
  },
  {
    id: 'tz-youxi',
    name: '临海尤溪绿道',
    region: 'taizhou',
    area: '临海市',
    distanceMeters: 13000,
    elevationGainMeters: 78,
    difficulty: 3,
    kind: 'endurance',
    description:
      '临海江南到尤溪的乡村绿道，13公里沿溪而建、绿林成荫，途经江南大峡谷与下涨村，前半段平缓、后段上坡挑战渐起，是城区边缘最易达的山水骑。',
    tips: '到下涨村上坡多，留好体力；绿道依水，雨后湿滑减速；村落可补给，节假日自驾多请避让。',
    source: '临海骑行攻略（临海旅游）：江南至尤溪段绿道总长13公里，依水而建、绿树成林，到下涨村上坡段较多；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['tz-youxi'] ?? [],
  },
  {
    id: 'tz-fangshan',
    name: '温岭方山探路',
    region: 'taizhou',
    area: '温岭市',
    distanceMeters: 59000,
    elevationGainMeters: 385,
    difficulty: 4,
    kind: 'climb',
    description:
      '温岭方山的经典探路，从大溪一带骑上雁荡余脉方山，约59公里、累计爬升353米，羊角峰、羊角洞与云霄寺散布山巅，登顶可看云海奇景，是温岭爬坡爱好者的日常。',
    tips: '常4+2自驾到山脚再骑，山路弯多坡陡；带足补给与车灯，下坡谨慎，雨后石材路面易滑。',
    source: 'Wikiloc 骑友轨迹：温岭骑行方山探路 59.26km、爬升353m（常自驾至大溪再骑上方山）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['tz-fangshan'] ?? [],
  },
  {
    id: 'nj-shecun',
    name: '佘村龙尚线',
    region: 'nanjing',
    area: '江宁区',
    distanceMeters: 8500,
    elevationGainMeters: 33,
    difficulty: 4,
    kind: 'endurance',
    description:
      '江宁佘村的山水短途线，约8.5公里从佘村明清代建筑群到横山水库、龙尚湖，虽短却上下坡密、S弯多，是城区边缘练控车与爬坡的“小硬核”。',
    tips: '坡度大、弯急，下坡控速靠右；佘村可补给餐饮，节假日村道自驾多，注意避让会车。',
    source: '国庆“南京City Ride地图”：田园佘村龙尚线 佘村—横山水库—龙尚湖，约8.5km，上下坡多、S弯较多；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['nj-shecun'] ?? [],
  },
  {
    id: 'nj-guli',
    name: '谷里线（大塘金-黄龙岘-石塘竹海）',
    region: 'nanjing',
    area: '江宁区',
    distanceMeters: 19000,
    elevationGainMeters: 60,
    difficulty: 3,
    kind: 'endurance',
    description:
      '江宁谷里的乡村骑行线，约19公里串起大塘金香草园、黄龙岘茶村与朱门人家直至石塘竹海，茶园、竹海与村落相间，起伏路练腿又不算太虐。',
    tips: '沿途驿站与农家多，补给方便；上下坡交替注意控速，节假日车流人流量大请仔细观察避让。',
    source: '国庆“南京City Ride地图”：田园风光·谷里线 谷里大塘金薰衣草园—黄龙岘—朱门人家—石塘竹海，约19km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['nj-guli'] ?? [],
  },
  {
    id: 'nj-laoshan',
    name: '老山环线',
    region: 'nanjing',
    area: '浦口区',
    distanceMeters: 15000,
    elevationGainMeters: 119,
    difficulty: 4,
    kind: 'climb',
    description:
      '南京近郊最壮丽的国家森林公园环线，约15公里穿行老山密林，珍七路如飘带缠绕山间、上下起伏千回百转，登俯江台可远眺长江，是江北车友的必征之地。',
    tips: '山路坡度起伏大，下坡务必检查刹车、控速避让会车；靠边骑行，带足水，珍七路段尤需专注。',
    source: '江北骑行推荐（腾讯新闻）：环老山骑行线 佛手湖—不老村—珍七路—四方当代艺术湖区—椅山俯江台—水墨大埝，全长约15km，山路起伏大；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['nj-laoshan'] ?? [],
  },
  {
    id: 'nj-shitang',
    name: '石塘竹海线',
    region: 'nanjing',
    area: '江宁区',
    distanceMeters: 40000,
    elevationGainMeters: 76,
    difficulty: 3,
    kind: 'endurance',
    description:
      '从中华门一路向南到横溪石塘竹海的“小九寨”长途线，约40公里经花神大道、宁丹公路的景观路到竹海，跨度长、风光好，是江宁最经典的单程打卡骑。',
    tips: '距离长，初次尝试可只骑其中一段；宁丹公路货车与弯道多，控速避让；自带补给，终点石塘竹海可休整。',
    source: '我苏网/搜狐南京骑行线路：江宁小九寨线 中华门城堡—花神大道—将军大道—宁丹公路—横溪镇—石塘竹海，骑行全长40km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['nj-shitang'] ?? [],
  },
  {
    id: 'cd-longquan-climb-race',
    name: '龙泉爬坡赛路线（飞龙湖→桃花故里）',
    region: 'chengdu',
    area: '龙泉驿区',
    distanceMeters: 7600,
    elevationGainMeters: 264,
    difficulty: 3,
    kind: 'climb',
    description:
      '龙泉山民间爬坡赛常用赛段，与 A 面相邻但走向不同，春季桃花季沿线景色最佳。',
    tips: '桃花季游客多、停车占道，建议非节假日刷坡；与 A 面可组合成小环。',
    source: '十一车队等骑友记载：龙泉爬坡赛（飞龙湖至桃花故里）赛段约 7.6km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['cd-longquan-climb-race'] ?? [],
  },
  {
    id: 'cd-panda',
    name: '熊猫绿道',
    region: 'chengdu',
    area: '成都市',
    distanceMeters: 100000,
    elevationGainMeters: 83,
    difficulty: 1,
    kind: 'endurance',
    description:
      '依托三环路辅道与社区绿带的环状绿道，深入主城区、节点密，是日常通勤与休闲骑行首选。',
    tips: '与三环机动车道相邻，过路口务必减速；适合碎片化短途骑行。',
    source: '成都市绿道资料：熊猫绿道（三环内）约 100km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['cd-panda'] ?? [],
  },
  {
    id: 'cd-qingcheng-dujiang',
    name: '青城山↔都江堰',
    region: 'chengdu',
    area: '都江堰市',
    distanceMeters: 15700,
    elevationGainMeters: 207,
    difficulty: 2,
    kind: 'endurance',
    description:
      '都江堰与青城山两大世界遗产间的平路连接线，沿途川西田园风光，适合串联两处景点的休闲骑行。',
    tips: '景区门口停车与人流多，注意减速；可结合绿道延伸为更长线路。',
    source: '骑友与地图资料记载：都江堰市区至青城山前山约 15.7km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['cd-qingcheng-dujiang'] ?? [],
  },
  {
    id: 'cd-haute-s1',
    name: 'Haute Route 大青城 S1',
    region: 'chengdu',
    area: '都江堰市',
    distanceMeters: 80000,
    elevationGainMeters: 282,
    difficulty: 4,
    kind: 'endurance',
    description:
      '大青城多日赛第一赛段，绕青城山—都江堰区域的起伏环路，长距离接中等爬升，是赛事级耐力路线。',
    tips: '赛段里程与爬升大，需自备补给；非赛事日可分段骑行。',
    source: 'Haute Route 大青城赛事资料：S1 赛段约 80km、累计爬升约 1600m+；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['cd-haute-s1'] ?? [],
  },
  {
    id: 'cd-haute-s2',
    name: 'Haute Route 大青城 S2',
    region: 'chengdu',
    area: '都江堰市',
    distanceMeters: 128000,
    elevationGainMeters: 2894,
    difficulty: 5,
    kind: 'endurance',
    description:
      '大青城第二赛段，跨越蒲虹路等山地的长距高爬升环路，融合平路、爬坡与下坡，难度最高。',
    tips: '含蒲虹路长爬坡，建议具备充分爬坡与补给能力；下坡弯道谨慎。',
    source: 'Haute Route 大青城赛事资料：S2 赛段约 128km、累计爬升约 2430m+；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS['cd-haute-s2'] ?? [],
  },
  {
    id: 'cd-luodai',
    name: '洛带古镇往返',
    region: 'chengdu',
    area: '龙泉驿区',
    distanceMeters: 50000,
    elevationGainMeters: 134,
    difficulty: 2,
    kind: 'endurance',
    description:
      '从城区向东骑往客家古镇洛带，平路为主、偶有缓坡，适合半日休闲往返。',
    tips: '进古镇前街道窄、游客多，下车道推行；可顺路接龙泉山刷坡。',
    source: '骑友社区记载：成都市区至洛带古镇往返约 50km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['cd-luodai'] ?? [],
  },
  {
    id: 'cd-longquan-loop',
    name: '龙泉小环线',
    region: 'chengdu',
    area: '龙泉驿区',
    distanceMeters: 80000,
    elevationGainMeters: 499,
    difficulty: 3,
    kind: 'endurance',
    description:
      '绕龙泉山一圈的闭合环线，平路接 A 面等爬坡，兼顾耐力与爬升，是周末百公里内的经典拉练。',
    tips: '环线含山路，备好爬坡齿比与补水；可与洛带、桃花故里组合。',
    source: '骑友社区记载：龙泉山区域小环线约 80km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['cd-longquan-loop'] ?? [],
  },
  {
    id: 'cq-geleshan',
    name: '歌乐山爬坡',
    region: 'chongqing',
    area: '沙坪坝区',
    distanceMeters: 15000,
    elevationGainMeters: 337,
    difficulty: 3,
    kind: 'climb',
    description:
      '沙坪坝城郊的红色景区山路，林荫好、坡道连绵，是主城西北侧入门级山地爬坡。',
    tips: '景区路段节假日车与游客多；烈士墓一带可补水，下坡注意弯道。',
    source: '骑友社区记载：童家桥—渣滓洞—歌乐山约 6km，沙坪坝—烈士墓—歌乐山约 15km 的盘山爬坡；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['cq-geleshan'] ?? [],
  },
  {
    id: 'cq-jinyun',
    name: '缙云山步道骑行',
    region: 'chongqing',
    area: '北碚区',
    distanceMeters: 7000,
    elevationGainMeters: 60,
    difficulty: 3,
    kind: 'climb',
    description:
      '北碚城郊缙云山的盘山通道，短爬坡接山林景观，是主城北侧轻量山地骑行。',
    tips: '部分步道禁止骑行或需推行，遵守管理标识；山顶可远眺嘉陵江。',
    source: '北碚本地资料：缙云山盘山步道/公路约 6–8km（以徒步为主，部分路段可骑行）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['cq-jinyun'] ?? [],
  },
  {
    id: 'cq-nanbin',
    name: '南滨路骑行',
    region: 'chongqing',
    area: '南岸区',
    distanceMeters: 15000,
    elevationGainMeters: 140,
    difficulty: 1,
    kind: 'endurance',
    description:
      '长江南岸的平坦滨江道，正对渝中半岛天际线，夜景极佳，是重庆最亲民的休闲骑行线。',
    tips: '夜间与周末人流车流大，降速礼让；沿线咖啡与观景台多，适合慢骑看江景。',
    source: '骑友社区记载：南滨路沿江骑行道约 15km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['cq-nanbin'] ?? [],
  },
  {
    id: 'cq-babin',
    name: '巴滨路骑行',
    region: 'chongqing',
    area: '巴南区',
    distanceMeters: 10000,
    elevationGainMeters: 252,
    difficulty: 1,
    kind: 'endurance',
    description:
      '巴南长江段的滨江平路，相对南滨路更安静开阔，适合家庭与新手的短途江景骑行。',
    tips: '部分路段与散步人流共用，注意减速；傍晚江风大，备薄外套。',
    source: '骑友社区记载：巴滨路滨江骑行道约 10km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['cq-babin'] ?? [],
  },
  {
    id: 'cq-zhaomu',
    name: '照母山爬坡',
    region: 'chongqing',
    area: '两江新区',
    distanceMeters: 3000,
    elevationGainMeters: 137,
    difficulty: 3,
    kind: 'climb',
    description:
      '两江新区照母山森林公园内的短山道，坡短陡、绿荫好，是新区车友就近刷坡的据点。',
    tips: '公园内人流与步道交错，注意避让；可往返重复训练。',
    source: '两江新区骑友记载：照母山盘山路段约 3km 的短爬坡；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['cq-zhaomu'] ?? [],
  },
  {
    id: 'cq-liangjiang-greenway2',
    name: '两江绿道 2 号（照母山—园博园—中央公园）',
    region: 'chongqing',
    area: '两江新区',
    distanceMeters: 19000,
    elevationGainMeters: 294,
    difficulty: 2,
    kind: 'endurance',
    description:
      '两江新区骨干绿道，串联照母山、园博园与中央公园三大绿地，路面平、隔离好，是新区最舒适的骑行环线。',
    tips: '绿道节点完善、可分段；周末公园人多，注意礼让。',
    source: '两江新区绿道规划资料：区级绿道 2 号线（照母山—园博园—中央公园）约 19km，全区级绿道约 75km、总绿道约 168km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS['cq-liangjiang-greenway2'] ?? [],
  },
  {
    id: 'cq-binjiang-full',
    name: '重庆滨江路全程',
    region: 'chongqing',
    area: '重庆市',
    distanceMeters: 40000,
    elevationGainMeters: 850,
    difficulty: 2,
    kind: 'endurance',
    description:
      '沿长江与嘉陵江滨江路串联的平路环线，集中展现重庆两江夜景与桥都风貌。',
    tips: '过桥与路口多、货车混行，谨慎骑行；可与两江四岸长线组合。',
    source: '骑友社区记载：重庆主城滨江路（南滨/巴滨/北滨等串联）骑行全程约 40km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['cq-binjiang-full'] ?? [],
  },
  {
    id: 'dl-erhai-loop',
    name: '环洱海',
    region: 'dali',
    area: '洱海',
    distanceMeters: 126000,
    elevationGainMeters: 1512,
    difficulty: 3,
    kind: 'endurance',
    description:
      '大理骑行的灵魂路线：沿环海路绕洱海一周，串联古城、喜洲、双廊与挖色，是每位到访骑友的必打卡百里湖环。',
    tips: '海西生态廊道禁机动车、最安全；海东环海东路大车多需靠边；高原紫外线强，全程防晒补水。',
    source: '环洱海骑行公开攻略里程约 120-131km（穷游 120 / 214 驿站 130 / 骑行营 131）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['dl-erhai-loop'] ?? [],
  },
  {
    id: 'dl-dali-xizhou',
    name: '大理古城—喜洲',
    region: 'dali',
    area: '大理·喜洲',
    distanceMeters: 18000,
    elevationGainMeters: 164,
    difficulty: 1,
    kind: 'endurance',
    description:
      '最轻松的苍洱短途：从大理古城沿洱海西岸直抵喜洲古镇，扁平好骑，是尝破酥粑粑、逛白族民居的半日骑。',
    tips: '几乎无爬升，亲子友好；可走生态廊道避车；喜洲午后人流大，早去更惬意。',
    source: '大理骑行公开攻略：古城至喜洲约 18km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['dl-dali-xizhou'] ?? [],
  },
  {
    id: 'dl-dali-shaxi',
    name: '大理—沙溪',
    region: 'dali',
    area: '剑川·沙溪',
    distanceMeters: 100000,
    elevationGainMeters: 904,
    difficulty: 4,
    kind: 'endurance',
    description:
      '通往茶马古道孤村的远骑：穿洱源坝子、翻罗坪山垭口直抵沙溪，是《去有风的地方》取景地的单车朝圣线。',
    tips: '含罗坪山爬坡段，预留体力；牛街至剑川盘山路注意落石；沙溪古镇禁机动车骑行。',
    source: '骑游攻略：大理古城至沙溪古镇约 100km（经洱源、牛街、剑川）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['dl-dali-shaxi'] ?? [],
  },
  {
    id: 'dl-shaxi-stone',
    name: '沙溪—石宝山环线',
    region: 'dali',
    area: '剑川·沙溪',
    distanceMeters: 30000,
    elevationGainMeters: 576,
    difficulty: 3,
    kind: 'endurance',
    description:
      '沙溪周边的田园石窟环：探访石宝山南诏石窟与华龙村稻田，平缓乡道与白族风情交织，是古镇休整日的轻骑。',
    tips: '路况以乡道为主、车少景美；可顺游石宝山景区；雨季注意田间路段泥泞。',
    source: '骑友攻略：沙溪—石宝山石窟—华龙村约 30km 环线；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['dl-shaxi-stone'] ?? [],
  },
  {
    id: 'gz-xinzhongzhou',
    name: '城市新中轴夜景线',
    region: 'guangzhou',
    area: '天河/海珠',
    distanceMeters: 14000,
    elevationGainMeters: 77,
    difficulty: 1,
    kind: 'endurance',
    description:
      '广州最具现代气息的夜骑线。沿新中轴线从花城广场南下，经省博、大剧院、海心沙，过二沙岛绿道，再到广州塔与会展中心，一路珠江灯火与小蛮腰同框，是城市地标打卡首选。',
    tips: '大部分为绿道与非机动车道、路面平整；周五晚 8 点猎德大桥有无人机表演；单车不可入花城广场，需先停好；夜骑装备前后灯。',
    source: '买购网《广州骑行路线推荐》：城市景观骑行路线（花城广场—海心沙—二沙岛—广州塔—会展中心）全程约 14 公里；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['gz-xinzhongzhou'] ?? [],
  },
  {
    id: 'gz-dafushan',
    name: '大夫山森林公园骑行',
    region: 'guangzhou',
    area: '番禺',
    distanceMeters: 10000,
    elevationGainMeters: 51,
    difficulty: 2,
    kind: 'endurance',
    description:
      '番禺的“城市氧吧”。大夫山绿道平坦、穿梭于聚秀湖、七盏灯水库与落羽杉林之间，长达数十公里四通八达，园内上千台单车可租，是广州最有人气的休闲骑行公园。',
    tips: '南门/北门均有租车点，单人车约 10–20 元/次、支持南北门互还；轻微上下坡，亲子三人车也能骑；山顶可俯瞰番禺；禁明火野炊。',
    source: '携程攻略：大夫山森林公园内骑行约 10 公里，绿道平坦且四通八达，北门南门可互还车；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['gz-dafushan'] ?? [],
  },
  {
    id: 'gz-guangfu',
    name: '广府水城线（云台花园—二沙岛）',
    region: 'guangzhou',
    area: '越秀/白云',
    distanceMeters: 30000,
    elevationGainMeters: 74,
    difficulty: 3,
    kind: 'endurance',
    description:
      '浓缩老广州精华的一纵一横绿道。北起白云山云台花园，经麓湖、越秀公园、镇海楼、东濠涌，沿沿江路至东山湖、二沙岛，串联五羊石像与星海音乐厅，勾起广府历史记忆。',
    tips: '主要沿越秀绿道，部分路段与机动车混行需控速；途经众多老广美食可补给；春夏绿荫好；长线建议白天分段或夜骑灯光段。',
    source: '买购网《广州骑行路线推荐》：广府水城骑行路线（白云山云台花园—麓湖—越秀公园—二沙岛）全程约 30 公里；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['gz-guangfu'] ?? [],
  },
  {
    id: 'gz-maofeng',
    name: '帽峰山大菜园爬坡',
    region: 'guangzhou',
    area: '白云',
    distanceMeters: 18000,
    elevationGainMeters: 466,
    difficulty: 3,
    kind: 'climb',
    description:
      '广州最高峰（帽峰山 534.9 米）下的招牌爬坡。大菜园路线全程 18 公里、累计爬升 300 米，森林覆盖率超 90%，弯道处可见“翡翠湖”，2025 年广州自行车联赛曾设专业组赛道。',
    tips: '下坡段落叶易打滑，建议碟刹；最大坡度 9% 需预留体力；白云区已办“竞速帽峰山”爬坡赛可作参考；山顶补给少，带足水。',
    source: '今日头条《广州绿骑行路线全攻略》：帽峰山·大菜园爬坡路线全程 18 公里、累计爬升 300 米、最大坡度 9%；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['gz-maofeng'] ?? [],
  },
  {
    id: 'gz-huolushan',
    name: '火炉山—凤凰山（火凤线）',
    region: 'guangzhou',
    area: '天河/白云',
    distanceMeters: 10500,
    elevationGainMeters: 74,
    difficulty: 4,
    kind: 'climb',
    description:
      '广州骑友公认的经典爬坡穿越线。火炉山经白架顶到凤凰山顶，约 10.5 公里爬升 700 米，土路台阶与盘山公路交替，是检验腿力的“硬核”训练场，也是火炉山—凤凰山的招牌串联。',
    tips: '部分山路为土径台阶，山地车更合适；上涂屋村有补给点；下坡陡需控速；新手建议只刷火炉山单段，量力而行。',
    source: '8264 户外论坛：传统火凤线（火炉山—凤凰山）里程约 10.5km、累计上升约 700 米；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['gz-huolushan'] ?? [],
  },
  {
    id: 'gz-liuxihe',
    name: '从化流溪河绿道',
    region: 'guangzhou',
    area: '从化',
    distanceMeters: 52000,
    elevationGainMeters: 159,
    difficulty: 3,
    kind: 'endurance',
    description:
      '北回归线上的绿色长廊。从化流溪河绿道全长 52 公里，春赏花、夏摘荔枝、秋品诗意、冬泡温泉，绿道沿一江碧水蜿蜒，串联森林公园、温泉小镇与古村落，是广州最治愈的远郊骑行。',
    tips: '绿道长，建议分段或自驾接驳；溪头村—流溪河森林公园段约 11 公里可单刷；雨后溪水更清适合亲水；中途驿站与温泉镇可补给。',
    source: '凤凰网：从化绿道全长 52 公里，沿流溪河而建，配套驿站完整；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['gz-liuxihe'] ?? [],
  },
  {
    id: 'gz-haioudao',
    name: '海鸥岛环岛骑旅',
    region: 'guangzhou',
    area: '番禺',
    distanceMeters: 40000,
    elevationGainMeters: 104,
    difficulty: 2,
    kind: 'endurance',
    description:
      '番禺狮子洋上的渔岛环线。海鸥岛环岛绿道约 40 公里，串起狮子洋海景、红树林湿地与渔港，2024 年增设多处海鲜市集驿站，是广州少有的“海景+海鲜”长途休闲骑。',
    tips: '海鸥大桥段约 500 米爬坡、坡度 5.2%，进阶骑手可冲；岛上海鲜市集现烤生蚝值得停；环岛风大注意保暖；建议白天往返。',
    source: '今日头条《广州绿骑行路线全攻略》：海鸥岛环岛绿道 40 公里，串联狮子洋风光、红树林湿地与渔港文化；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['gz-haioudao'] ?? [],
  },
  {
    id: 'gz-huadu',
    name: '花都绿道（芙蓉嶂—天马河）',
    region: 'guangzhou',
    area: '花都',
    distanceMeters: 30000,
    elevationGainMeters: 34,
    difficulty: 3,
    kind: 'endurance',
    description:
      '广东 4 号绿道的起点段。从芙蓉嶂水库沿河而下，经秀全水库、天马河，全程近 30 公里，青山碧水、乡村羊肠小道与湿地景观交替，是花都山水田园骑行的代表线。',
    tips: '芙蓉驿站、秀全驿站、天马河驿站可休息租车；沿途樱花/杜鹃景观带季节性强；部分沙石路段控速；自驾接驳更轻松。',
    source: '凤凰网：花都绿道（芙蓉嶂—天马河）全程近 30 公里，为广东 4 号绿道起点段；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['gz-huadu'] ?? [],
  },
  {
    id: 'gz-baiyunshan',
    name: '白云山盘山公路爬坡',
    region: 'guangzhou',
    area: '白云',
    distanceMeters: 6000,
    elevationGainMeters: 73,
    difficulty: 3,
    kind: 'climb',
    description:
      '“羊城第一秀”的入门爬坡。从云台花园沿盘山公路缓上摩星岭，约 6 公里、爬升三百余米，登顶可俯瞰珠江新城与小蛮腰，是市中心最近的山地训练线。',
    tips: '夜爬建议走盘山公路、路灯更安全；周末索道排队长，骑车不受影响；山顶豆腐花、白云猪手可补给；下坡弯多控速。',
    source: '穷游攻略：白云山盘山公路从云台花园入口至摩星岭约 6 公里；摩星岭海拔 382 米（去哪儿攻略）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['gz-baiyunshan'] ?? [],
  },
  {
    id: 'gz-ersha',
    name: '二沙岛环岛碧道',
    region: 'guangzhou',
    area: '越秀',
    distanceMeters: 7300,
    elevationGainMeters: 32,
    difficulty: 1,
    kind: 'endurance',
    description:
      '珠江中的文艺江心岛。二沙岛环岛碧道约 7.3 公里，串联艺术公园、宏城公园、传祺公园与星海音乐厅、广东美术馆，三级骑行道系统人车分流，是市中心最惬意的环岛骑。',
    tips: '缓跑径禁自行车，请走骑行道；宏城公园是拍广州塔“神仙机位”；岛上禁机动车喧嚣，适合亲子晨骑夜骑；接阅江路可拉长。',
    source: '百度百科/广州碧道：二沙岛环岛碧道全长约 7.3 公里，串联五大公园与星海音乐厅、广东美术馆；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['gz-ersha'] ?? [],
  },
  {
    id: 'gz-licha',
    name: '荔湖环岛碧道',
    region: 'guangzhou',
    area: '增城',
    distanceMeters: 3600,
    elevationGainMeters: 13,
    difficulty: 1,
    kind: 'endurance',
    description:
      '增城新城区的亲水小环线。荔湖环岛碧道岸线 3.6 公里，整合山、水、园、林，可骑车散步赏山水，夜间灯光如项链，是增城市民一小时闲暇的轻松骑。',
    tips: '短平环线，亲子与新手首选；环湖一圈约 1 小时；碧道加装灯光适合夜骑；接增江画廊可拉长里程。',
    source: '澎湃新闻：荔湖环岛碧道（增城新城大道与增城第一中学拐角）岸线总长 3.6 公里；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['gz-licha'] ?? [],
  },
  {
    id: 'hn-haikou-wenchang',
    name: '海口—文昌',
    region: 'hainan',
    area: '东线北段',
    distanceMeters: 85000,
    elevationGainMeters: 365,
    difficulty: 2,
    kind: 'endurance',
    description:
      '东线第一站，从海口骑楼老街出发沿S201省道向东北，经大致坡到文昌，平路缓坡、椰林夹道，配套成熟，是环岛热身首选段。',
    tips: '全程平缓少坡，新手友好；文昌可游东郊椰林、宋氏祖居；夏季正午暴晒，早出发并做好防晒。',
    source: '骑行圈路书（磨房）：海口—文昌 85公里，沿S201省道平路为主；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-haikou-wenchang'] ?? [],
  },
  {
    id: 'hn-wanning-lingshui',
    name: '万宁—陵水',
    region: 'hainan',
    area: '东线南段',
    distanceMeters: 61000,
    elevationGainMeters: 398,
    difficulty: 2,
    kind: 'endurance',
    description:
      '万宁经兴隆向西再折南到陵水，翻过环岛第一座小山（约3公里上坡、最大坡度12%），随后清水湾、海棠湾海景渐开。',
    tips: '兴隆后有3公里爬坡注意节奏；陵水可游南湾猴岛；补给充足但正午炎热，宜早骑。',
    source: '骑行圈路书（磨房）：博鳌—陵水121公里（含万宁、兴隆），万宁—陵水约61公里；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-wanning-lingshui'] ?? [],
  },
  {
    id: 'hn-lingshui-sanya',
    name: '陵水—三亚',
    region: 'hainan',
    area: '东线终点',
    distanceMeters: 70000,
    elevationGainMeters: 541,
    difficulty: 2,
    kind: 'endurance',
    description:
      '东线收官段，从陵水沿G223西南到三亚，经海棠湾、亚龙湾，过一小段山路（上坡约3公里），海景与热带城市风光收尾。',
    tips: '三亚住宿多；亚龙湾、天涯海角可顺路玩；入城车流大，走非机动车道；注意防晒。',
    source: '骑行圈路书（磨房）：陵水—三亚 70公里，沿G223；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-lingshui-sanya'] ?? [],
  },
  {
    id: 'hn-changjiang-danzhou',
    name: '昌江—儋州',
    region: 'hainan',
    area: '西线北段',
    distanceMeters: 54000,
    elevationGainMeters: 594,
    difficulty: 2,
    kind: 'endurance',
    description:
      '昌江经叉河、雅星到儋州，G225沿线多缓坡，可顺访千年古盐田与热带植物园，是西线通往海口的过渡段。',
    tips: '儋州住宿集中在解放路；下坡多总体轻松；注意牛羊穿路，乡村路段减速。',
    source: '骑行圈路书（磨房）：昌江—儋州约54公里（东方—儋州124公里分段）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-changjiang-danzhou'] ?? [],
  },
  {
    id: 'hn-chengmai-haikou',
    name: '澄迈—海口',
    region: 'hainan',
    area: '西线终点',
    distanceMeters: 67000,
    elevationGainMeters: 463,
    difficulty: 2,
    kind: 'endurance',
    description:
      '澄迈经老城回到海口，沿G225接滨海大道入城，平路为主，标志西线环岛完成，可领环岛奖牌证书。',
    tips: '入海口车多，走非机动车道；老城、澄迈补给方便；完成西线注意总结体力。',
    source: '骑行圈路书（磨房）：老城—海口约67公里（儋州—海口133公里分段）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-chengmai-haikou'] ?? [],
  },
  {
    id: 'hn-sanya-wuzhishan',
    name: '三亚—五指山',
    region: 'hainan',
    area: '中线南段',
    distanceMeters: 82000,
    elevationGainMeters: 1241,
    difficulty: 4,
    kind: 'climb',
    description:
      '中线南段，三亚经响水沿G224向东北深入黎苗山区，连续盘山爬升，途经槟榔谷与甘石岭，是中线最考验体力的一段。',
    tips: '爬坡前在响水补给；下坡弯多减速；山区阵雨多带雨衣；信号弱提前下离线地图。',
    source: '骑行圈路书（磨房）：三亚—五指山 82公里，沿G224翻越山岭；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-sanya-wuzhishan'] ?? [],
  },
  {
    id: 'hn-wuzhishan-qiongzhong',
    name: '五指山—琼中',
    region: 'hainan',
    area: '中线',
    distanceMeters: 74000,
    elevationGainMeters: 1693,
    difficulty: 4,
    kind: 'climb',
    description:
      '五指山过阿陀岭后一路起伏向北到琼中，途经毛阳与鹦哥岭边缘，雨林与梯田相伴，是中线爬升后相对舒展的一段。',
    tips: '出五指山先爬10公里再放坡；琼中可住宿；山区天气多变，备雨具与防风。',
    source: '骑行圈路书（磨房）：五指山—琼中 74公里（五指山—屯昌126公里分段）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-wuzhishan-qiongzhong'] ?? [],
  },
  {
    id: 'hz-xihu',
    name: '环西湖骑行线',
    region: 'hangzhou',
    area: '西湖区',
    distanceMeters: 12210,
    elevationGainMeters: 69,
    difficulty: 3,
    kind: 'endurance',
    description:
      '杭州最经典的入门环湖线，沿北山路、杨公堤、南山路串联断桥、苏堤、雷峰塔等核心景点，路面平坦、车流可控，是租辆共享单车就能刷的休闲骑。杨公堤六座拱桥起伏是全程唯一的“小挑战”。',
    tips: '周末西湖景区单双号限行，建议工作日或清晨骑行；杨公堤林荫段戴车灯，人流密集处减速避让行人。',
    source: '杭州市体育局推介杭州8条经典骑行线路（西湖观景·环西湖骑行线 12.21km，难度3）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS['hz-xihu'] ?? [],
  },
  {
    id: 'hz-longjing',
    name: '龙井爬坡线',
    region: 'hangzhou',
    area: '西湖区',
    distanceMeters: 10000,
    elevationGainMeters: 24,
    difficulty: 4,
    kind: 'climb',
    description:
      '被骑友奉为“杭州骑行圣路”的经典爬坡，从杨公堤拐入龙井路后连续2.6公里上坡，坡度8%—10%，穿过茶园时满目青绿、空气里都是炒茶香。新手可在茶农铺子歇脚再推车缓行。',
    tips: '龙井路下坡可达40km/h，务必戴头盔；夏季夜骑人气旺，注意弯道与往来车辆，带足水。',
    source: '杭州文广旅游发布龙井爬坡线：少年宫至龙井村全程约10km，爬坡段2.6km、坡度约8%-10%，称“杭州骑行圣路”；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['hz-longjing'] ?? [],
  },
  {
    id: 'hz-qingshanhu',
    name: '环青山湖骑行线',
    region: 'hangzhou',
    area: '临安区',
    distanceMeters: 42195,
    elevationGainMeters: 90,
    difficulty: 3,
    kind: 'endurance',
    description:
      '临安青山湖畔的环湖绿道，全长42.195公里，水面开阔、杉林夹道，被水面与山色包裹，是杭州近郊少有的“湖光+森林”长距离平路环线，适合周末半日耐力拉练。',
    tips: '绿道平缓可匀速刷圈；节假日游客多，沿湖段注意避让行人，夏季防晒补水，预留返程体力。',
    source: '杭州市体育局推介杭州8条经典骑行线路（青山觅绿·环青山湖骑行绿道 42.195km，难度3）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['hz-qingshanhu'] ?? [],
  },
  {
    id: 'hz-tongjianhu',
    name: '环铜鉴湖骑行线',
    region: 'hangzhou',
    area: '西湖区',
    distanceMeters: 7580,
    elevationGainMeters: 22,
    difficulty: 2,
    kind: 'endurance',
    description:
      '双浦铜鉴湖景区内的环湖短线路，全长7.58公里，田埂、湖岸与花海交织，路面平、距离短，是亲子与新手最友好的“微度假”骑行，顺路还能看杭城难得的乡土水乡风光。',
    tips: '里程短可反复刷；景区禁止明火与露营，爱护草坪；春秋花季人流量大，错峰更舒服。',
    source: '杭州市体育局推介杭州8条经典骑行线路（铜鉴赏花·环铜鉴湖骑行线 7.58km，难度2）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS['hz-tongjianhu'] ?? [],
  },
  {
    id: 'hz-xianghu',
    name: '环湘湖骑行线',
    region: 'hangzhou',
    area: '萧山区',
    distanceMeters: 14000,
    elevationGainMeters: 34,
    difficulty: 2,
    kind: 'endurance',
    description:
      '萧山湘湖的环湖经典线，环一、二期约14公里，沿越王路、老虎洞、跨湖桥串联越王城山、初阳台等吴越文化景点。湖面平静、绿道隔离完善，是杭州南片日常训练与休闲骑的首选。',
    tips: '三期七彩绿道7.6km更轻松，适合亲子；环线设多个租车点，节假日景区人多，注意慢行避让。',
    source: '萧山区政府/湘管委推荐环湘湖一、二期全程14km（强度中等）；另三期七彩绿道7.6km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['hz-xianghu'] ?? [],
  },
  {
    id: 'hz-qianjiang',
    name: '钱江两岸骑行线',
    region: 'hangzhou',
    area: '上城区/滨江',
    distanceMeters: 33650,
    elevationGainMeters: 56,
    difficulty: 4,
    kind: 'endurance',
    description:
      '城市阳台出发，跨彭埠大桥、钱江世纪城、奥体中心，再沿闻涛路返回，环钱江两岸约33.65公里。一边是现代天际线、一边是辽阔江面，是杭州最能感受“大都市气质”的滨江耐力线。',
    tips: '过桥与隧道段开前后车灯、靠右骑行；江边风大，逆风段消耗翻倍，注意补给与避让行人。',
    source: '杭州市体育局推介杭州8条经典骑行线路（钱江望潮·钱江两岸骑行线 33.65km，难度4）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS['hz-qianjiang'] ?? [],
  },
  {
    id: 'hz-guchengmen',
    name: '古城门骑行线',
    region: 'hangzhou',
    area: '上城区',
    distanceMeters: 16180,
    elevationGainMeters: 81,
    difficulty: 3,
    kind: 'endurance',
    description:
      '串联古武林门、钱塘门、清波门、凤山门、候潮门、望江门等十座古城门的文化骑行线，穿行老城街巷与南山路，把杭州的城墙记忆和市井烟火一根线串起，适合慢骑打卡。',
    tips: '线路穿越老城区，红绿灯与行人多，遵守交规、单排骑行；部分古城门仅余地名，留意导航节点。',
    source: '杭州市体育局推介杭州8条经典骑行线路（古城遗风·杭州古城门骑行线 16.18km，难度3）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS['hz-guchengmen'] ?? [],
  },
  {
    id: 'hz-yinghua',
    name: '闻涛路樱花大道',
    region: 'hangzhou',
    area: '滨江区',
    distanceMeters: 4810,
    elevationGainMeters: 20,
    difficulty: 1,
    kind: 'endurance',
    description:
      '滨江闻涛路的短途休闲线，全长4.81公里，从复兴大桥到一桥底沿秋石绿道而行，春天樱花夹道、平日江景开阔，是新手、亲子和夜骑最轻松的入门路线。',
    tips: '距离短、坡度平，适合带娃与热身；樱花季人车密集，慢行避让，注意江边横风。',
    source: '杭州市体育局推介杭州8条经典骑行线路（樱花漫舞·樱花大道骑行线 4.81km，难度1）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS['hz-yinghua'] ?? [],
  },
  {
    id: 'km-gaohai-road',
    name: '高海公路',
    region: 'kunming',
    area: '西山·高海公路',
    distanceMeters: 41800,
    elevationGainMeters: 795,
    difficulty: 3,
    kind: 'endurance',
    description:
      '贴着滇池西岸的景观公路：高海公路依山傍水，一侧青山一侧湖，是昆明骑友最喜欢的湖西刷坡与往返线路。',
    tips: '多为往返骑行，注意对向车流；临崖路段风大，下坡集中注意力；可接海口继续环湖南岸。',
    source: '昆明高海公路公开里程：高峣至海口约 41.8km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['km-gaohai-road'] ?? [],
  },
  {
    id: 'km-baozhusi-climb',
    name: '宝珠寺·宝花路爬坡',
    region: 'kunming',
    area: '盘龙·双龙乡',
    distanceMeters: 8000,
    elevationGainMeters: 87,
    difficulty: 4,
    kind: 'climb',
    description:
      '昆明东北郊的短陡爬坡：宝花路盘山直上宝珠寺，短短数公里爬升近五百米，是城区附近最虐的练腿路段。',
    tips: '坡度集中、极易爆心跳，建议小盘慢踩；山顶宝珠寺可补给休整；雨季路面湿滑需控速。',
    source: '昆明文旅 / 西山发布：宝珠寺、宝花路爬坡约 8km，累计爬升近 500m；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['km-baozhusi-climb'] ?? [],
  },
  {
    id: 'km-yiliang-68',
    name: '宜良68道拐',
    region: 'kunming',
    area: '宜良',
    distanceMeters: 7340,
    elevationGainMeters: 488,
    difficulty: 5,
    kind: 'climb',
    description:
      '云南最著名的魔鬼发卡弯：短短 7 公里六十八道急弯，平均坡度 7%，是检验爬坡技术与意志的全国知名地标。',
    tips: '坡陡弯急、下坡极险，务必检查刹车；山路窄无缓冲，严禁占道；建议工作日前往避免游客车流。',
    source: '新华网 / 昆明市政府：宜良靖安哨68道拐全长 7.34km，爬升约 488m，平均坡度约 7%；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['km-yiliang-68'] ?? [],
  },
  {
    id: 'km-jiaozishan-172',
    name: '轿子雪山（昆明—轿子山）',
    region: 'kunming',
    area: '禄劝·轿子山',
    distanceMeters: 172000,
    elevationGainMeters: 3044,
    difficulty: 5,
    kind: 'endurance',
    description:
      '昆明最硬核的长途爬坡：一路向北深入禄劝，从平原爬向滇中第一峰，是本地长途骑行与高原适应的终极拉练。',
    tips: '单程百七十公里、海拔持续抬升，需充分补给与保暖；山区天气多变，山顶常临近冰点，带好冲锋衣。',
    source: '骑友 / 赛事资料：昆明市区至轿子山单程约 172km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['km-jiaozishan-172'] ?? [],
  },
  {
    id: 'km-liangwangshan',
    name: '梁王山往返',
    region: 'kunming',
    area: '呈贡东·梁王山',
    distanceMeters: 108820,
    elevationGainMeters: 1388,
    difficulty: 5,
    kind: 'climb',
    description:
      '雄踞滇池与阳宗海之间的观景高峰：梁王山主峰 2820 米，是昆明周边视野最开阔的爬坡，可同时俯瞰两湖。',
    tips: '10.83km 主爬坡段平均坡度不低，预留体力；山顶风大气温低；往返里程长，注意补水与返程逆风。',
    source: '骑友轨迹：昆明南至梁王山往返约 108.82km，累计爬升约 1135m（主爬坡段 10.83km 爬升约 524m，主峰 2820m）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['km-liangwangshan'] ?? [],
  },
  {
    id: 'km-yangzonghai-40',
    name: '阳宗海环湖绿道',
    region: 'kunming',
    area: '阳宗海',
    distanceMeters: 40000,
    elevationGainMeters: 1035,
    difficulty: 3,
    kind: 'endurance',
    description:
      '昆明东南的温泉湖环线：阳宗海环湖绿道沿湖铺设，温泉小镇与湿地相伴，是新兴的近郊休闲骑行目的地。',
    tips: '绿道较新、路面好；可顺游汤池温泉补给；环湖多段临水，注意横风与骑行安全。',
    source: '昆明市政府（2026-07）：阳宗海环湖绿道约 40km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['km-yangzonghai-40'] ?? [],
  },
  {
    id: 'km-qingxiaxia',
    name: '青龙峡',
    region: 'kunming',
    area: '安宁西·青龙峡',
    distanceMeters: 90000,
    elevationGainMeters: 784,
    difficulty: 4,
    kind: 'endurance',
    description:
      '昆明西郊的峡谷远骑：沿螳螂川河谷深入安宁青龙峡，山林峡谷与河谷交替，是城西长途拉练的热门方向。',
    tips: '部分路段与 320 国道共线，大车多需靠边；峡谷段逆风强，预留体力返程。',
    source: '昆明骑友公开轨迹：昆明至青龙峡约 90km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['km-qingxiaxia'] ?? [],
  },
  {
    id: 'km-jindian-yeyahu',
    name: '金殿—野鸭湖',
    region: 'kunming',
    area: '盘龙东北·野鸭湖',
    distanceMeters: 80000,
    elevationGainMeters: 793,
    difficulty: 4,
    kind: 'endurance',
    description:
      '从金殿延伸到野鸭湖的中距离环：穿行城郊林海与水库村道，起伏多于短环，是周末耐力进阶的实用路线。',
    tips: '野鸭湖段路窄弯多，会车小心；里程接近百公里，规划好补给点。',
    source: '昆明骑友公开轨迹：金殿经野鸭湖环线约 80km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['km-jindian-yeyahu'] ?? [],
  },
  {
    id: 'sh-sheshan',
    name: '环佘山',
    region: 'shanghai',
    area: '松江',
    distanceMeters: 14000,
    elevationGainMeters: 84,
    difficulty: 2,
    kind: 'endurance',
    description:
      '上海少有的山地骑行场景：从佘山地铁站出发环绕佘山，林间绿道起伏平缓，途经天主教堂与月湖，是市区骑友最常走的入门环线。',
    tips: '路面平整、坡度极缓，适合入门与亲子；节假日游客多注意行人；可串联辰山植物园延长里程。',
    source: '上海佘山国家旅游度假区官方发布骑行路线（全长 14km，起点佘山地铁站）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS.sheshan ?? [],
  },
  {
    id: 'sh-jiufeng',
    name: '上山下坑穿越九峰',
    region: 'shanghai',
    area: '松江',
    distanceMeters: 17000,
    elevationGainMeters: 38,
    difficulty: 3,
    kind: 'endurance',
    description:
      '佘山度假区三条官方路线里最具挑战的一条：穿越九峰十二山，起伏路串联山林与深坑地貌，是上海能找到的最接近爬坡的路线。',
    tips: '连续起伏比里程更耗体力，建议带足水；部分林道落叶湿滑需控速；周末上午人少体验更好。',
    source: '上海佘山国家旅游度假区官方发布骑行路线（全长 17km，起点西佘山园）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS.jiufeng ?? [],
  },
  {
    id: 'sh-fulushan',
    name: '福禄山水',
    region: 'shanghai',
    area: '松江',
    distanceMeters: 9000,
    elevationGainMeters: 90,
    difficulty: 2,
    kind: 'endurance',
    description:
      '三条官方路线中最轻松的一条：从东佘山园穿行山水之间，短平快，适合作为佘山骑行的热身段或亲子休闲骑。',
    tips: '里程短可反复刷圈；沿线有景区与餐饮，补给方便；春秋两季景色最佳。',
    source: '上海佘山国家旅游度假区官方发布骑行路线（全长 9km，起点东佘山园）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS.fulushan ?? [],
  },
  {
    id: 'sh-chongming',
    name: '环崇明岛',
    region: 'shanghai',
    area: '崇明',
    distanceMeters: 108600,
    elevationGainMeters: 33,
    difficulty: 4,
    kind: 'endurance',
    description:
      '上海长距离骑行的天花板：沿陈海公路、北沿公路绕行崇明岛，串联西沙湿地与东平森林公园，全程平路，考验的是耐力与补给节奏。',
    tips: '全程几乎无爬升但距离长，务必早出发并带足补给；岛上风大，逆风段体力消耗翻倍；注意轮渡与桥隧通行规定。',
    source: '2025 上海城市业余联赛 TREK100 暨环崇明公路自行车公开赛官方路书（108.6km）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS.chongming ?? [],
  },
  {
    id: 'sh-dianshanhu',
    name: '环淀山湖',
    region: 'shanghai',
    area: '青浦',
    distanceMeters: 50000,
    elevationGainMeters: 17,
    difficulty: 3,
    kind: 'endurance',
    description:
      '上海最大的淡水湖环线：沿湖大道与乡村道交替，蔡浜村一段 270 度湖景是全程精华，是沪上骑友必打卡的经典环线。',
    tips: '顺时针出发可先走掉车流较大的沪青平公路段；节假日真爱码头一带人流车流密集需推车通行；夏季注意防晒补水。',
    source: '上海体育 / 青浦体育官方推荐环湖骑行线路（环湖一周约 50km）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS.dianshanhu ?? [],
  },
  {
    id: 'sh-jiabei',
    name: '嘉北郊野公园绿道',
    region: 'shanghai',
    area: '嘉定',
    distanceMeters: 8000,
    elevationGainMeters: 3,
    difficulty: 1,
    kind: 'endurance',
    description:
      '上海北部的大型郊野公园绿道：农田、花海与片林连成一片，路面平坦宽阔，园内还有上海唯一的林下山地自行车赛道可进阶挑战。',
    tips: '入门与亲子首选，园内可租车；春季花海季人流量大；园区禁止明火与放风筝，不可过夜露营。',
    source: '上海体育官方推荐郊野公园骑行绿道（园内生态绿道环线约 8km）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS.jiabei ?? [],
  },
  {
    id: 'sz-shenzhenwan',
    name: '深圳湾滨海骑行',
    region: 'shenzhen',
    area: '南山/福田',
    distanceMeters: 13000,
    elevationGainMeters: 47,
    difficulty: 1,
    kind: 'endurance',
    description:
      '深圳入门骑行的标杆线。沿深圳湾滨海休闲带从红树林到海上世界，一侧城市天际线、一侧滩涂候鸟，全程平坦无陡坡，补给与驿站密集，亲子与新手上手首选。',
    tips: '周末及节假日白天公园禁共享单车，建议傍晚后骑；9 号线深圳湾公园站直达；人流密集减速避让；秋季观鸟最佳。',
    source: '深圳骑行道路指引（骑行深圳）：深圳湾绿道（红树林—海上世界）约 13 公里，跨福田、南山两区滨海长廊；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['sz-shenzhenwan'] ?? [],
  },
  {
    id: 'sz-yantian-haibin',
    name: '盐田海滨绿道',
    region: 'shenzhen',
    area: '盐田',
    distanceMeters: 19500,
    elevationGainMeters: 481,
    difficulty: 3,
    kind: 'endurance',
    description:
      '号称“世界最长海滨玉带”，西起中英街古塔公园、东至背仔角，串起沙头角、盐田港、大小梅沙。左手海、右手山，灯塔图书馆与海上悬桥是招牌，是深圳看海骑行的氛围天花板。',
    tips: '中午海边无遮挡紫外线强，备冰袖帽子；大梅沙旺季人流量大，骑行道与步道分流；背仔角尽头无补给，提前带水。',
    source: '深圳骑行道路指引（骑行深圳）：盐田海滨绿道全程 19.5km、累计上升 393m、爬坡里程 11.1km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['sz-yantian-haibin'] ?? [],
  },
  {
    id: 'sz-yangmeikeng',
    name: '杨梅坑—鹿嘴山庄（新东绿道）',
    region: 'shenzhen',
    area: '大鹏',
    distanceMeters: 12000,
    elevationGainMeters: 50,
    difficulty: 2,
    kind: 'endurance',
    description:
      '大鹏半岛最美溪谷海岸线。沿新东路从南澳方向经杨梅坑到鹿嘴山庄，碧海蓝天、平缓沿海公路，《美人鱼》取景地鹿嘴山庄在海角尽头，是深圳最治愈的滨海骑行段。',
    tips: '往返距离不短，体力一般可租电助力车；早 9 点前出发避开烈日与周末人流；餐饮少，自带干粮饮水。',
    source: '深圳骑行道路指引/深圳十大绿道：新东绿道（新东路西入口至鹿嘴山庄）全长约 12km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-yangmeikeng'] ?? [],
  },
  {
    id: 'sz-dadingshan',
    name: '大顶岭绿道（虹桥公园）',
    region: 'shenzhen',
    area: '光明',
    distanceMeters: 10420,
    elevationGainMeters: 47,
    difficulty: 3,
    kind: 'endurance',
    description:
      '光明招牌的“山湖马拉松绿道”，全长 10.42 公里串联虹桥公园与浮桥、探桥、悬桥三座白色网红桥。田园、山林与稻田交织，是深圳拍照与骑行兼得的标志性线路。',
    tips: '周末及节假日禁止骑行，仅工作日可骑；桥体有台阶需推行小段；夏季林荫好但午后仍晒，备水防晒。',
    source: '深圳骑行道路指引（骑行深圳）：大顶岭绿道和虹桥公园全长 10.42km，含浮桥/探桥/悬桥；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-dadingshan'] ?? [],
  },
  {
    id: 'sz-fenghuangshan',
    name: '凤凰山绿道',
    region: 'shenzhen',
    area: '宝安',
    distanceMeters: 9100,
    elevationGainMeters: 23,
    difficulty: 4,
    kind: 'climb',
    description:
      '宝安“第一山”的骑行秘境，全长 9.1 公里沿山地林道与滨水道铺设，曾办多届山地自行车挑战赛。前半段爬坡、后半段放坡滑行，途经凤岩古庙与客家村落，山顶可西眺伶仃洋。',
    tips: '下坡需控车速避让行人；山脚美食街 13 点前人少；森林防火区禁明火；周末登山人流大，早出发体验更佳。',
    source: '深圳城管绿道里程发布：凤凰山绿道全长 9.1km，难度系数“困难”，曾办山地自行车挑战赛；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-fenghuangshan'] ?? [],
  },
  {
    id: 'sz-yinhu',
    name: '银湖山郊野径',
    region: 'shenzhen',
    area: '罗湖/龙岗',
    distanceMeters: 12000,
    elevationGainMeters: 252,
    difficulty: 4,
    kind: 'climb',
    description:
      '横亘罗湖—龙岗交界的郊野径，骑行可通行段约 12 公里，含大爬坡与弯道，野趣十足。山顶可远眺福田与坂田，是深圳少有的“进城即山”的进阶耐力线。',
    tips: '郊野段无补水点，上山前在地铁站补水；雨后土面湿滑建议徒步鞋；结伴骑行，部分路段信号弱。',
    source: '深圳骑行道路指引（骑行深圳）：银湖山郊野径骑行可通行段约 12km，难度★★★★有大爬坡及弯道；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-yinhu'] ?? [],
  },
  {
    id: 'sz-dashahe',
    name: '大沙河生态长廊',
    region: 'shenzhen',
    area: '南山',
    distanceMeters: 13700,
    elevationGainMeters: 59,
    difficulty: 2,
    kind: 'endurance',
    description:
      '被称为“深圳塞纳河”的滨水长廊，从长岭陂水库到深圳湾入海口全长 13.7 公里，分学院、城市森林、活力水岸三段。几乎无陡坡，串联大学城与人才公园，通勤骑行人气最高。',
    tips: '地铁多点直达入口，共享单车可入；西段周末及节假日禁自行车；沿途驿站咖啡齐全，夏季遮阴好。',
    source: '深圳骑行道路指引（骑行深圳）：大沙河生态长廊全长 13.7km，分学院/城市森林/活力水岸三段；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['sz-dashahe'] ?? [],
  },
  {
    id: 'sz-shihu',
    name: '环石岩湖绿道',
    region: 'shenzhen',
    area: '宝安',
    distanceMeters: 30800,
    elevationGainMeters: 183,
    difficulty: 3,
    kind: 'endurance',
    description:
      '深圳最长的环湖绿道，30.8 公里环绕石岩湖，串联陌上花、青草排等主题公园。起伏平缓的大环线，四季花草轮替、多处草坪野餐点，亲子花海环湖与耐力训练皆宜。',
    tips: '环线长可分段骑行；无地铁直达建议自驾或打车到俯仰之间公园；共享单车禁行，需自带车；沿途驿站补水方便。',
    source: '深圳骑行道路指引（骑行深圳）：环石岩湖骑行道全长 30.8km，为深圳最长环湖绿道；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-shihu'] ?? [],
  },
  {
    id: 'sz-luohu5',
    name: '罗湖绿道5号线（梧桐绿道）',
    region: 'shenzhen',
    area: '罗湖',
    distanceMeters: 14000,
    elevationGainMeters: 88,
    difficulty: 3,
    kind: 'endurance',
    description:
      '被市民票选“深圳最美绿道”，沿深圳水库与梧桐山河而建，约 14 公里分山水休闲、果林野趣、河滨沁爽三段。一路山水相伴，远眺梧桐山云雾，是罗湖骑友的周末标配。',
    tips: '起点东湖公园南门可租车；绿道深处便利店少，自带水与零食；雨后路面湿滑慢行；保护水库鸟类禁喧哗。',
    source: '深圳十大绿道（深圳城管）：梧桐绿道（罗湖绿道5号线）约 14 公里，沿深圳水库与梧桐山河；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-luohu5'] ?? [],
  },
  {
    id: 'sz-taojin',
    name: '淘金山绿道',
    region: 'shenzhen',
    area: '罗湖',
    distanceMeters: 7070,
    elevationGainMeters: 188,
    difficulty: 2,
    kind: 'endurance',
    description:
      '藏在罗湖的城中山林氧吧，起于翠湖社区公园、终至沙湾路，全长 7.07 公里。风铃木与紫薇夹道，13 处景观节点串联深圳水库，是情侣与遛娃都友好的平缓绿道。',
    tips: '禁止共享单车，需自带车；全 WiFi 覆盖、设补给站与卫生间；午后林荫好；接梧桐绿道可组合拉长。',
    source: '深圳骑行道路指引（骑行深圳）：淘金山绿道全长 7.07km，起翠湖社区公园终至沙湾路；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['sz-taojin'] ?? [],
  },
  {
    id: 'sz-futianhe',
    name: '福田河绿道',
    region: 'shenzhen',
    area: '福田',
    distanceMeters: 6100,
    elevationGainMeters: 16,
    difficulty: 1,
    kind: 'endurance',
    description:
      '藏在市中心楼宇间的“绿丝带”，北起笔架山南至滨河路，全长 6.1 公里沿福田河而建。连通两大公园、鸟语水声，是通勤休闲两用的短途吸氧线。',
    tips: '地铁笔架山/中心公园站直达，共享单车可入；沿河密林遮阴好，夏不晒；适合晨骑或夜骑；人车混行减速。',
    source: '深圳骑行道路指引（骑行深圳）：福田河绿道全长约 6.1km，北起笔架山南至滨河路；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-futianhe'] ?? [],
  },
  {
    id: 'sz-lixinhui',
    name: '环立新湖绿道',
    region: 'shenzhen',
    area: '宝安',
    distanceMeters: 8800,
    elevationGainMeters: 44,
    difficulty: 2,
    kind: 'endurance',
    description:
      '凤凰山下的环湖绿道，约 8.8 公里环绕立新湖，因地制宜设林中栈道、观湖平台与沿湖步道。西望珠江口、南邻望牛亭，是宝安西部安静的休闲平路环线。',
    tips: '仅限自行车、共享单车禁入；纯平路适合亲子；环湖一圈约 1 小时；湖心岛与观景绿港为打卡点。',
    source: '深圳城管绿道里程发布：环立新湖绿道约 8.8km，环绕立新湖、凤凰山下；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-lixinhui'] ?? [],
  },
  {
    id: 'sz-xilihu',
    name: '环西丽湖碧道',
    region: 'shenzhen',
    area: '南山',
    distanceMeters: 15000,
    elevationGainMeters: 81,
    difficulty: 2,
    kind: 'endurance',
    description:
      '西丽湖畔的生态碧道，主线约 15 公里从西丽湖大坝经大磡村到白芒村，荔枝林与缓坡相间，吸氧治愈型，可与大沙河组成长距离组合线。',
    tips: '建议走 10 公里精华段；衔接大沙河可拉到深圳湾；共享单车可入部分段；夏日林荫好但需补水防晒。',
    source: '深圳骑行道路指引（骑行深圳）：环西丽湖碧道主线 15km（建议 10km），西丽湖大坝—白芒村；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['sz-xilihu'] ?? [],
  },
  {
    id: 'tz-kuocang',
    name: '括苍山爬坡',
    region: 'taizhou',
    area: '临海市',
    distanceMeters: 25000,
    elevationGainMeters: 458,
    difficulty: 5,
    kind: 'climb',
    description:
      '浙东第一高峰的硬核攀登，从山脚牌楼一路盘旋25公里、爬升1300多米到米筛浪顶，风机阵列与云海相伴。是台州爬坡的“天花板”，也是柴古唐斯破风见山等赛事的舞台。',
    tips: 'HC级长坡极耗体力，带足水与能量；山顶风大温差大，下坡控速；冬季易结冰，雾天勿强行冲顶。',
    source: '临海旅游/中国新闻网浙江：括苍山主峰米筛浪海拔1382.4米，连续爬坡25公里、爬升1300余米，爬坡赛道HC级（最高级别）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['tz-kuocang'] ?? [],
  },
  {
    id: 'tz-tiantai',
    name: '天台山霞客路爬坡',
    region: 'taizhou',
    area: '天台县',
    distanceMeters: 24000,
    elevationGainMeters: 854,
    difficulty: 4,
    kind: 'climb',
    description:
      '“礼佛问道霞客路”的经典爬坡赛道，从国清寺沿天北公路经赤城山、桐柏宫直上华顶，约24公里爬升798米，陡缓坡分布均衡，云雾仙境路段被骑友称为“浙里的川藏线”。',
    tips: '穿县城到桐柏岭头约9km爬400余米可先热身；山顶华顶海拔千米注意保暖；隧道与弯道多，下坡开灯控速。',
    source: '浙江在线台州频道（天台山全国山地自行车爬坡赛）：国清景区至华顶书院赛道约24km、海拔上升约798米；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    tracks: NATIONAL_TRACKS['tz-tiantai'] ?? [],
  },
  {
    id: 'wh-donghu-loop',
    name: '东湖绿道环线',
    region: 'wuhan',
    area: '武昌·东湖风景区',
    distanceMeters: 105000,
    elevationGainMeters: 193,
    difficulty: 3,
    kind: 'endurance',
    description:
      '武汉骑行的门面环线：沿东湖绿道串联听涛、磨山、落雁、白马四大景区，湖光山色与城市绿道交织，是国内少有的城市中心百里湖环。',
    tips: '全程绿道禁机动车，安全性高；里程长建议早出发并分段补给；节假日磨山、落雁段人多，错峰体验更好。',
    source: '东湖风景区管委会 / 长江日报：2024 年东湖绿道三期贯通后全线约 105km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['wh-donghu-loop'] ?? [],
  },
  {
    id: 'wh-moshan-climb',
    name: '磨山爬坡',
    region: 'wuhan',
    area: '武昌·东湖磨山',
    distanceMeters: 12000,
    elevationGainMeters: 62,
    difficulty: 4,
    kind: 'climb',
    description:
      '武汉骑友的爬坡启蒙地：从湖边盘绕而上至磨山顶，虽不高却坡陡弯急，是检验腿力和齿比的城市短爬首选。',
    tips: '坡陡建议提前切小盘；清晨雾气大、视线一般，注意控速；山顶可俯瞰东湖全景，适合拍照。',
    source: '东湖绿道官方分段里程（磨山道约 12km，为武汉经典爬坡段）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['wh-moshan-climb'] ?? [],
  },
  {
    id: 'wh-donghu-huzhongdao',
    name: '东湖绿道·湖中道段',
    region: 'wuhan',
    area: '武昌·东湖',
    distanceMeters: 16000,
    elevationGainMeters: 53,
    difficulty: 2,
    kind: 'endurance',
    description:
      '东湖绿道最精华的一段：沿湖岸从听涛景区直抵磨山，路面平整、视线开阔，是日常刷圈与新手拉练的高频路线。',
    tips: '与 105km 环线可自由拼接；沿途驿站可补水补给；周末午后人流密集，建议工作日前往。',
    source: '东湖绿道官方分段里程（听涛—磨山湖中道段约 16km）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['wh-donghu-huzhongdao'] ?? [],
  },
  {
    id: 'wh-houguanhu-20',
    name: '后官湖绿道·短环',
    region: 'wuhan',
    area: '蔡甸',
    distanceMeters: 20000,
    elevationGainMeters: 35,
    difficulty: 2,
    kind: 'endurance',
    description:
      '蔡甸的亲水绿道短环：沿后官湖岸线铺设，路面宽阔平缓，是汉阳、蔡甸骑友日常刷圈的入门首选。',
    tips: '绿道全线禁行机动车；可随时并入全长 110km 大环挑战；湖边风大，注意防风外套。',
    source: '武汉市园林和林业局 / 人民日报：后官湖绿道设 20km 精品环线；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['wh-houguanhu-20'] ?? [],
  },
  {
    id: 'wh-tangxunhu',
    name: '汤逊湖环湖绿道',
    region: 'wuhan',
    area: '江夏·汤逊湖',
    distanceMeters: 28000,
    elevationGainMeters: 135,
    difficulty: 2,
    kind: 'endurance',
    description:
      '藏身光谷的近郊湖环：汤逊湖是武汉面积最大的城中湖之一，环湖绿道短平快，是上班族下班刷圈的便利选择。',
    tips: '环湖路多段与市政道路共用，留意电动车；可拼接江夏其他绿道延长里程。',
    source: '去哪儿等公开游记：汤逊湖环湖绿道约 28km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['wh-tangxunhu'] ?? [],
  },
  {
    id: 'wh-longquan-18',
    name: '龙泉山亲子线',
    region: 'wuhan',
    area: '江夏·龙泉山',
    distanceMeters: 18000,
    elevationGainMeters: 74,
    difficulty: 1,
    kind: 'endurance',
    description:
      '江夏龙泉山的轻松小环：明代楚王陵园区林道平缓、历史文化浓，是最适合带娃入门的短途骑行。',
    tips: '景区内道路平整、车少；可顺游楚王陵与094 影视基地；春秋季景色最佳。',
    source: '江夏龙泉山风景区公开活动里程：亲子骑行线约 18km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['wh-longquan-18'] ?? [],
  },
  {
    id: 'wh-longquan-80',
    name: '龙泉山长线',
    region: 'wuhan',
    area: '江夏·龙泉山',
    distanceMeters: 80000,
    elevationGainMeters: 142,
    difficulty: 4,
    kind: 'endurance',
    description:
      '龙泉山的长距离挑战：把丘陵环线向外延展，串联更多湖畔与村落，是江夏本地骑友周末刷里程的主力路线。',
    tips: '里程接近百公里，注意补给节奏；后半段丘陵起伏易透支，预留余力返程。',
    source: '江夏龙泉山公开活动里程：长距离挑战线约 80km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['wh-longquan-80'] ?? [],
  },
  {
    id: 'wh-jinyinhu',
    name: '金银湖绿道',
    region: 'wuhan',
    area: '东西湖·金银湖',
    distanceMeters: 20000,
    elevationGainMeters: 44,
    difficulty: 1,
    kind: 'endurance',
    description:
      '汉口西北的亲水小环：金银湖湿地绿道平缓开阔，是东西湖与汉口骑友晨晚练、亲子骑行的便利去处。',
    tips: '全程平坦、几乎无爬升；湖区风大注意保暖；可串联张公堤绿道延长。',
    source: '东西湖区公开绿道里程：金银湖绿道约 20km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['wh-jinyinhu'] ?? [],
  },
  {
    id: 'wh-zhanggongdi',
    name: '张公堤绿道',
    region: 'wuhan',
    area: '东西湖·张公堤',
    distanceMeters: 30000,
    elevationGainMeters: 20,
    difficulty: 2,
    kind: 'endurance',
    description:
      '汉口北部的城市堤防绿道：沿张公堤铺设，隔绝货运大道的喧嚣，是汉口骑友日常耐力训练的安全长廊。',
    tips: '堤顶路面平整、无机动车；可向西接金银湖、向东连汉口江滩；逆风段体力消耗大。',
    source: '武汉市园林和林业局：张公堤城市绿道约 30km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['wh-zhanggongdi'] ?? [],
  },
  {
    id: 'xm-huandao',
    name: '环岛路滨海赛道',
    region: 'xiamen',
    area: '思明区',
    distanceMeters: 23000,
    elevationGainMeters: 168,
    difficulty: 2,
    kind: 'endurance',
    description:
      '厦门骑行天花板，依山傍海的世界级滨海赛道。串联白城、曾厝垵、胡里山、会展中心、观音山，全程听海看椰林，入门到进阶皆宜。',
    tips: '海风大、游客多，建议清晨或傍晚骑行；沿途补给充足，注意避让行人。',
    source: '厦门文旅：环岛路海岸段约22.5公里（单程，白城—五通），被称为中国最美滨海骑行赛道；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['xm-huandao'] ?? [],
  },
  {
    id: 'xm-xinglinwan',
    name: '环杏林湾海上自行车道',
    region: 'xiamen',
    area: '集美区',
    distanceMeters: 26000,
    elevationGainMeters: 54,
    difficulty: 2,
    kind: 'endurance',
    description:
      '中国第一条海上自行车道，环绕杏林湾，全长约26公里。红色飘带横跨部分湾面，一侧园博苑、一侧嘉庚建筑，城在海上、海在城中。',
    tips: '含约2.6公里海上段，风大注意平衡；环线较长，建议带足补给。',
    source: '骑行推荐：环杏林湾海上自行车道全长约26公里（集杏海堤—园博苑—水上运动中心），中国第一条海上自行车道；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['xm-xinglinwan'] ?? [],
  },
  {
    id: 'xm-yuandang',
    name: '环筼筜湖绿道',
    region: 'xiamen',
    area: '思明区',
    distanceMeters: 12000,
    elevationGainMeters: 37,
    difficulty: 1,
    kind: 'endurance',
    description:
      '环筼筜湖绿道约12公里，串联筼筜湖、松柏湖、地湖、天湖，是厦门“城市会客厅”。路面平坦、绿树成荫，白鹭翩飞、高楼在侧。',
    tips: '全线平坦无爬升，适合晨练夜骑；西堤咖啡街可中途歇脚。',
    source: '新福建/台海网：环筼筜湖一圈约12公里，串联筼筜湖、松柏湖、地湖、天湖；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['xm-yuandang'] ?? [],
  },
  {
    id: 'xm-huandong-tongan',
    name: '环东浪漫线同安段',
    region: 'xiamen',
    area: '同安区',
    distanceMeters: 10400,
    elevationGainMeters: 49,
    difficulty: 1,
    kind: 'endurance',
    description:
      '环东浪漫线同安段（二期同安段）约10.4公里彩虹跑道，串联官浔溪、丙洲大桥与下潭尾湾，海岸线开阔、人少景阔，进阶拉练好选择。',
    tips: '与一期相接可连骑；海风大注意保暖，沿线驿站补给有限。',
    source: '厦门本地宝：滨海旅游浪漫线二期同安段长约10.4公里（官浔溪—丙洲大桥东），已建成投用；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xm-huandong-tongan'] ?? [],
  },
  {
    id: 'xm-dongping',
    name: '东坪山盘山公路',
    region: 'xiamen',
    area: '思明区',
    distanceMeters: 20000,
    elevationGainMeters: 456,
    difficulty: 4,
    kind: 'climb',
    description:
      '东坪山盘山公路约20公里，人烟稀少、三角梅夹道，是厦门练爬坡的圣地。经文屏路、怪坡、梅海岭、东坪山公园，一路绿树成荫。',
    tips: '坡度不陡但里程长，适合爬坡训练；山顶可俯瞰本岛与鼓浪屿。',
    source: '今日头条骑行推荐：东坪山盘山公路全长约20公里（文屏路—怪坡—梅海岭—东坪山公园—金鸡亭）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['xm-dongping'] ?? [],
  },
  {
    id: 'xm-wenzeng',
    name: '文曾路爬坡',
    region: 'xiamen',
    area: '思明区',
    distanceMeters: 5330,
    elevationGainMeters: 147,
    difficulty: 3,
    kind: 'climb',
    description:
      '文曾路约5.33公里经典爬坡，连接文屏路与植物园，号称“厦门最美观山道路”。一路怪坡、花溪相伴，高差约80米，短而爽快。',
    tips: '短爬坡热身佳，注意下坡控速；春季三角梅与樱花盛开。',
    source: '骑行攻略：文曾路约5.33公里，高差约80米，号称厦门最美观山道路；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['xm-wenzeng'] ?? [],
  },
  {
    id: 'xm-tianzhu',
    name: '天竺山山地骑行',
    region: 'xiamen',
    area: '海沧区',
    distanceMeters: 50000,
    elevationGainMeters: 115,
    difficulty: 5,
    kind: 'climb',
    description:
      '天竺山是厦门体量最大的山地骑行线，全程约50公里，杏林内茂至天竺山西门约8公里连续上坡，林密谷深，适合长距离耐力与爬坡训练。',
    tips: '线路长、爬升集中，务必结伴并带足补给；山区信号弱，提前规划返程。',
    source: '骑行攻略：天竺山线路约50公里，杏林内茂—天竺山西门约8公里连续上坡；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xm-tianzhu'] ?? [],
  },
  {
    id: 'xa-lishan-loop',
    name: '骊山环山路（华清宫→仁宗庙）',
    region: 'xian',
    area: '临潼区',
    distanceMeters: 57000,
    elevationGainMeters: 169,
    difficulty: 4,
    kind: 'climb',
    description:
      '绕骊山半圈的环山公路，串联华清宫、仁宗庙等景点，坡缓但连绵，可俯瞰临潼城区与渭河平原。',
    tips: '骊山景区路段节假日车多，尽量工作日或早间骑行；仁宗庙一带风口较大，注意保暖。',
    source: '新浪报道：华清宫至仁宗庙环线约 55–60km 的骊山环山骑行路线；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xa-lishan-loop'] ?? [],
  },
  {
    id: 'xa-citywall',
    name: '西安城墙骑行',
    region: 'xian',
    area: '碑林区',
    distanceMeters: 13740,
    elevationGainMeters: 43,
    difficulty: 1,
    kind: 'endurance',
    description:
      '全国唯一可骑行的完整古城墙闭环，顶面平整、坡度极小，是游客与新手体验城墙全景的最佳路线。',
    tips: '城墙骑行需购票并按规定时段骑行；租车点在南门、东门等登城口，傍晚登城光线与风最舒适。',
    source: '多个来源一致记载西安明城墙周长约 13.74km，城墙上设有骑行道；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['xa-citywall'] ?? [],
  },
  {
    id: 'xa-chanba-loop',
    name: '浐灞生态区环线',
    region: 'xian',
    area: '未央区/灞桥区',
    distanceMeters: 60000,
    elevationGainMeters: 243,
    difficulty: 2,
    kind: 'endurance',
    description:
      '沿浐河、灞河水系串联生态公园与湿地，路面平、绿荫多，是西安城区最舒适的休闲长距离环线之一。',
    tips: '河堤路部分段落与跑步、散步人流共用，节假日需降速礼让；沿途多个出入口可随时缩短里程。',
    source: '今日头条等媒体报道浐灞生态区环线骑行约 60km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xa-chanba-loop'] ?? [],
  },
  {
    id: 'xa-sanhe-chanba',
    name: '三河一山浐灞河绿道',
    region: 'xian',
    area: '灞桥区',
    distanceMeters: 47700,
    elevationGainMeters: 73,
    difficulty: 2,
    kind: 'endurance',
    description:
      '西安「三河一山」绿道网络的浐灞段，专用骑行道与机动车隔离，串联广运潭、世博园等节点，亲水且平缓。',
    tips: '绿道标识清晰、补给方便，适合家庭与新手；夏季午后暴晒，建议晨骑或傍晚。',
    source: 'ChinaDaily 报道：三河一山绿道浐灞河主线（及支线）约 47.7km / 29km 的滨水骑行道；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xa-sanhe-chanba'] ?? [],
  },
  {
    id: 'xa-cuihua-climb',
    name: '翠华山（太乙宫→天池）',
    region: 'xian',
    area: '长安区',
    distanceMeters: 13000,
    elevationGainMeters: 125,
    difficulty: 3,
    kind: 'climb',
    description:
      '从太乙宫镇沿盘山公路直上翠华山天池，短而陡的入门级山道爬坡，终点可俯瞰山崩地貌与湖泊。',
    tips: '景区内车辆与游客混杂，控制车速；天池附近可补水，下山注意连续弯道。',
    source: '骑友社区记载：太乙宫至翠华山天池单程约 13km，盘山公路持续爬升；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xa-cuihua-climb'] ?? [],
  },
  {
    id: 'xa-cuihua-round',
    name: '市中心→翠华山往返',
    region: 'xian',
    area: '长安区',
    distanceMeters: 80000,
    elevationGainMeters: 486,
    difficulty: 3,
    kind: 'endurance',
    description:
      '从城区沿子午大道、太乙宫一路向南进山再折返，平路接短爬坡的组合，适合周末半日耐力骑行。',
    tips: '出城段子午大道非机动车道条件一般，注意大车；进山前在太乙宫补给。',
    source: '骑友社区记载：西安市区至翠华山往返约 80km、累计爬升约 500m；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['xa-cuihua-round'] ?? [],
  },
  {
    id: 'xa-weihe-city',
    name: '渭河绿道（三河一山西安城市段）',
    region: 'xian',
    area: '未央区',
    distanceMeters: 27220,
    elevationGainMeters: 10,
    difficulty: 1,
    kind: 'endurance',
    description:
      '渭河南岸城市段专用骑行绿道，全程平坦、与车流完全隔离，是市区最长的连续平路骑行道之一。',
    tips: '河风较大、遮阴少，秋冬注意保暖防晒；绿道多处接驳地铁，可分段骑行。',
    source: '西安市生态环境局（xaepb）发布的三河一山绿道资料：渭河西安城市段骑行道约 27.22km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xa-weihe-city'] ?? [],
  },
  {
    id: 'xa-fenshuiling',
    name: '秦岭分水岭',
    region: 'xian',
    area: '长安 · 秦岭',
    distanceMeters: 34280,
    elevationGainMeters: 1595,
    difficulty: 5,
    kind: 'climb',
    description:
      '西安爬坡的终极试炼：沿 G210 从沣峪口一路爬升至长江黄河分水岭垭口（海拔约 2030m），34km 连续爬升，陕西车友的「驾考」路线。',
    tips: '垭口气温比市区低 8–10°C 带防风；沣峪内村镇可补水；周末车流大建议早出发；冬季背阴路面可能结冰。',
    source: '中国秦岭分水岭自行车爬坡赛规程',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS.fxl ?? [],
  },
  {
    id: 'hz-longjingbei',
    name: '龙井北坡',
    region: 'hangzhou',
    area: '西湖景区',
    distanceMeters: 2600,
    elevationGainMeters: 130,
    difficulty: 2,
    kind: 'climb',
    description:
      '杭州市区最友好的刷坡路：从龙井路口沿龙井路盘旋至龙井村，茶山夹道、坡度均匀，日常训练与休闲骑两相宜。',
    tips: '坡度均匀（5% 上下），适合入门刷坡；3–5 月茶季游客多注意行人；可串满觉陇路、龙井西路组成小环线。',
    source: '捷安特官方骑游地图（均坡 5.05%）',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS.lj ?? [],
  },
  {
    id: 'tz-kuocangshan',
    name: '括苍山',
    region: 'taizhou',
    area: '临海',
    distanceMeters: 26310,
    elevationGainMeters: 1490,
    difficulty: 5,
    kind: 'climb',
    description:
      '浙东最高峰的进阶爬坡：沿风电公路盘旋登顶括苍山（米筛浪 1382m），云海与风车阵列是台州骑友的年度朝圣。',
    tips: '26km 平均坡度 5.4%，山顶温差大必带防风；山顶无补给，出发前在山下吃饱；清晨云海概率高。',
    source: '野途网爬坡赛段（均坡 5.36%）',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS.kcs ?? [],
  },
  {
    id: 'sz-wutongshan',
    name: '梧桐山',
    region: 'shenzhen',
    area: '罗湖',
    distanceMeters: 6280,
    elevationGainMeters: 533,
    difficulty: 4,
    kind: 'climb',
    description:
      '深圳市区最近的硬核爬坡：沿梧桐山北路盘旋至好汉坡，平均坡度 8.5%，深圳车友的晨练打卡地。',
    tips: '全年可骑，夏季高温建议清晨出发；山上补水点有限；下坡弯多路窄控速，周末晨间行人和车都多。',
    source: '野途网爬坡赛段（均坡 8.46%）',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS.wts ?? [],
  },
  {
    id: 'cd-longquanshan',
    name: '龙泉山 A 面',
    region: 'chengdu',
    area: '龙泉驿',
    distanceMeters: 7700,
    elevationGainMeters: 370,
    difficulty: 3,
    kind: 'climb',
    description:
      '成都平原东缘的日常练坡场：沿 G318 老路上山至山泉镇（桃花故里），春季桃李花开时风景最佳。',
    tips: '3 月桃花季车流人流大注意安全；坡度舒缓适合入门耐力训练；可与下坡串成环线，山顶有农家乐补给。',
    source: '成都骑行社区攻略（坡度 2–6%）',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS.lqs ?? [],
  },
  {
    id: 'km-maomaoqing',
    name: '西山猫猫箐',
    region: 'kunming',
    area: '西山',
    distanceMeters: 6000,
    elevationGainMeters: 436,
    difficulty: 4,
    kind: 'climb',
    description:
      '春城最近的看海爬坡：盘山公路爬上西山猫猫箐村，回望滇池与昆明城景，四季如春的打卡坡。',
    tips: '全年适宜，冬季清晨路面可能有霜注意防滑；山顶村落有农家补给；紧邻西山风景区，节假日车多。',
    source: '昆明信息港实测里程 + 骑行码表爬升口径',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS.mmq ?? [],
  },
  {
    id: 'cd-qingcheng-full',
    name: '成都→青城山（不含后山）',
    region: 'chengdu',
    area: '都江堰市',
    distanceMeters: 130000,
    elevationGainMeters: 329,
    difficulty: 3,
    kind: 'endurance',
    description:
      '从成都主城一路向西北直抵青城山的百公里级往返，以平路为主、终点接景区，适合一日长途。',
    tips: '出城段国道货车多，注意安全；青城山前可补水补给后再返程。',
    source: '骑友社区记载：成都市区至青城山（不含后山）往返约 130km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['cd-qingcheng-full'] ?? [],
  },
  {
    id: 'cq-nanshan',
    name: '南山骑行环线',
    region: 'chongqing',
    area: '南岸区',
    distanceMeters: 20000,
    elevationGainMeters: 637,
    difficulty: 3,
    kind: 'endurance',
    description:
      '重庆主城最热门的近郊山线，盘山路串起南山植物园与观景台，可俯瞰渝中半岛与两江夜景。',
    tips: '上山弯道多、与车道共用，控速靠右；节假日自驾多，建议清晨骑行。',
    source: '骑友社区记载：南滨公园—洋人街—纳溪沟—南山植物园—南山一带环线约 20km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['cq-nanshan'] ?? [],
  },
  {
    id: 'cq-liangjiang',
    name: '两江四岸骑行',
    region: 'chongqing',
    area: '重庆市',
    distanceMeters: 132000,
    elevationGainMeters: 910,
    difficulty: 3,
    kind: 'endurance',
    description:
      '环绕渝中、串联南滨/北滨/巴滨等岸线的超长滨水环线，以平路为主、景观密集，是重庆城市骑行的旗舰路线。',
    tips: '全程长且跨多桥，规划好过江桥与补给点；建议分多段完成。',
    source: '重庆两江四岸治理资料与骑友记载：串联长江、嘉陵江四岸的滨水骑行全程约 132km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['cq-liangjiang'] ?? [],
  },
  {
    id: 'dl-erhai-east',
    name: '洱海海东线（古城—双廊）',
    region: 'dali',
    area: '洱海东岸',
    distanceMeters: 73100,
    elevationGainMeters: 608,
    difficulty: 3,
    kind: 'endurance',
    description:
      '洱海东岸的观海长骑：经环海东路过海东、文笔村、挖色直达双廊，临崖观海、逆风挑战，是与海西截然不同的硬核半环。',
    tips: '环海东路大车多、临崖弯急，务必靠边控速；逆风段消耗大，预留体力；双廊可补给休整。',
    source: '骑部落 / 穷游洱海骑行攻略：海东线古城—双廊约 73.1km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['dl-erhai-east'] ?? [],
  },
  {
    id: 'gz-zengjiang',
    name: '增江画廊骑行',
    region: 'guangzhou',
    area: '增城',
    distanceMeters: 30000,
    elevationGainMeters: 26,
    difficulty: 2,
    kind: 'endurance',
    description:
      '增城绿道的精华段，中国自行车运动协会认证的全国精品线路。沿增江河畔约 30 公里，串联荔湖湿地、莲塘春色、何仙姑景区等，南北贯穿、环山绕水，是广州少有的长距离亲水骑行网。',
    tips: '4 月荔枝花海、11 月落羽杉红叶为季节限定；沿途二十余驿站可歇脚；年接待骑行游客超 50 万人次；平路为主适合耐力拉练。',
    source: '中国自行车运动协会认证“2023 中国户外运动精品骑行线路”：增城·增江画廊段约 30 公里，穿越荔湖湿地、莲塘春色等 12 个景区；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['gz-zengjiang'] ?? [],
  },
  {
    id: 'hn-qiongzhong-tunchang',
    name: '琼中—屯昌',
    region: 'hainan',
    area: '中线',
    distanceMeters: 52000,
    elevationGainMeters: 308,
    difficulty: 3,
    kind: 'endurance',
    description:
      '琼中向东北到屯昌，G224沿线以田园与低丘起伏路为主，已无大坡，节奏轻松，是中线进入海口前的缓冲段。',
    tips: '起伏路注意节奏分配；屯昌补给方便；临近海口车流渐多，走安全车道。',
    source: '骑行圈路书（磨房）：琼中—屯昌 52公里（五指山—屯昌126公里分段）；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-qiongzhong-tunchang'] ?? [],
  },
  {
    id: 'hn-tunchang-haikou',
    name: '屯昌—海口',
    region: 'hainan',
    area: '中线北段',
    distanceMeters: 91000,
    elevationGainMeters: 388,
    difficulty: 3,
    kind: 'endurance',
    description:
      '中线收官，屯昌经永兴到海口，总体起伏平路，可顺访海南热带野生动植物园，标志中线环岛完成。',
    tips: '入海口车多走辅道；永兴可补水；完成中线注意总结，海口驿站可领奖牌。',
    source: '骑行圈路书（磨房）：屯昌—海口 91公里；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['hn-tunchang-haikou'] ?? [],
  },
  {
    id: 'qd-badaguan',
    name: '八大关—栈桥 老城滨海',
    region: 'qingdao',
    area: '市南区',
    distanceMeters: 6000,
    elevationGainMeters: 44,
    difficulty: 1,
    kind: 'endurance',
    description:
      '老城最核心的短途线，八大关红瓦绿树、太平角临海木栈道、栈桥回澜阁一路串起，路况平坦、景点密集，适合散步式慢骑与拍照。',
    tips: '景区步道人车混行，务必控速；单行道多，注意导航；适合清晨或傍晚避开游客高峰。',
    source: '骑友社区：八大关经太平角、南海路至栈桥约6公里；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['qd-badaguan'] ?? [],
  },
  {
    id: 'qh-jiangxigou-heimahe',
    name: '江西沟—黑马河',
    region: 'qinghai',
    area: '环湖西南',
    distanceMeters: 47000,
    elevationGainMeters: 100,
    difficulty: 3,
    kind: 'endurance',
    description:
      '沿G109向西南到黑马河，青海湖与海心山一路相伴，平缓路段居多，黑马河是看日出与住宿的核心节点。',
    tips: '黑马河看日出需早起；沿途宾馆多无需担心食宿；高原风冷，清晨厚外套必备。',
    source: '骑行圈路书（qixingquan）：江西沟—黑马河 47公里；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['qh-jiangxigou-heimahe'] ?? [],
  },
  {
    id: 'qh-xihai-jinyintan',
    name: '西海镇—金银滩',
    region: 'qinghai',
    area: '西海镇周边',
    distanceMeters: 10000,
    elevationGainMeters: 130,
    difficulty: 2,
    kind: 'endurance',
    description:
      '西海镇到金银滩草原的短途休闲线，《在那遥远的地方》诞生地，7月野花遍野、雪山在望，适合适应海拔与热身。',
    tips: '几乎无坡、轻松；海拔3000米仍要慢热；傍晚无光污染可看星空；注意防风。',
    source: '腾讯地图：西海镇—金银滩骑行约10.1公里；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'C',
    tracks: NATIONAL_TRACKS['qh-xihai-jinyintan'] ?? [],
  },
  {
    id: 'sz-maluan',
    name: '马峦山绿道',
    region: 'shenzhen',
    area: '坪山',
    distanceMeters: 9400,
    elevationGainMeters: 229,
    difficulty: 3,
    kind: 'climb',
    description:
      '坪山新开放的 9.4 公里山林绿道，沥青新铺、专属骑行道，蜿蜒于水库、瀑布与梅花亭之间。连绵起伏的山地路段是天然的爬坡训练场，也是深圳少见的“山野骑行”体验。',
    tips: '坡度变化大，新手谨慎全程骑行；北门驿站可租山地车与电助力车；园内无自动补给站，自带水；雨季路面湿滑控速。',
    source: '坪山发布/深圳东部文化：马峦山郊野公园新开放绿道全长 9.4km，沥青专属骑行道、连绵起伏有爬坡；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    tracks: NATIONAL_TRACKS['sz-maluan'] ?? [],
  },
  {
    id: 'xm-huandong',
    name: '环东海域浪漫线一期',
    region: 'xiamen',
    area: '同安区',
    distanceMeters: 7900,
    elevationGainMeters: 51,
    difficulty: 1,
    kind: 'endurance',
    description:
      '环东海域滨海旅游浪漫线一期示范段约7.9公里，红蓝彩虹跑道依黄金沙滩而建，最左侧蓝道专供骑行。海天一色，厦门新晋网红打卡地。',
    tips: '蓝色车道为骑行专用，右侧红道为跑步；周末人多，注意避让。',
    source: '厦门本地宝/厦门文旅：环东海域滨海旅游浪漫线一期约7.9公里（集美大桥—官浔溪口），红蓝彩虹跑道；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xm-huandong'] ?? [],
  },
  {
    id: 'xa-changan-cityloop',
    name: '长安城市环线',
    region: 'xian',
    area: '长安区',
    distanceMeters: 120000,
    elevationGainMeters: 330,
    difficulty: 3,
    kind: 'endurance',
    description:
      '绕长安区城郊的闭合环线，城郊道路与近山路段结合，平路为主、偶有缓坡，适合一日百公里拉练。',
    tips: '环线穿越多个乡镇，注意交叉口与农用车；建议自备补胎工具与能量补给。',
    source: '今日头条等媒体报道长安区城市骑行环线约 120km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'B',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xa-changan-cityloop'] ?? [],
  },
  {
    id: 'xa-weihe-xixian',
    name: '渭河绿道（西咸段）',
    region: 'xian',
    area: '西咸新区',
    distanceMeters: 64650,
    elevationGainMeters: 49,
    difficulty: 1,
    kind: 'endurance',
    description:
      '渭河上游西咸新区段的滨河绿道，路面平坦、视野开阔，是城市西北侧最长的连续平路骑行道。',
    tips: '河堤风大、服务点稀疏，出发前备足饮水；可与西安城市段绿道衔接成更长线路。',
    source: '西安市生态环境局（xaepb）三河一山绿道资料：渭河西咸新区段骑行道约 64.65km；爬升为 SRTM 90m 公开高程估算',
    sourceGrade: 'A',
    geometryScope: 'core',
    tracks: NATIONAL_TRACKS['xa-weihe-xixian'] ?? [],
  },

]
